// kge-stories.js — the parallel texts.
//
// Every sentence carries three versions and the working behind them:
//
//   en    the English
//   kn    Kannada: script, transliteration, and a say-it-aloud respelling
//   el    Greek:   script, transliteration, and a say-it-aloud respelling
//   gloss word-by-word, so you can see which piece means what
//   note  what the two languages did differently from English, and why
//
// Transliteration is ISO 15919 for Kannada (ā ī ū ē ō ṭ ḍ ṇ ḷ ś ṣ) and a
// standard romanisation for Greek. The `say` line is not a scholarly system —
// it is what an English speaker should do with their mouth, with the stressed
// syllable in capitals.
//
// Two things to know while reading the notes. Kannada is SOV: the verb goes
// last, and grammatical roles are marked by endings glued onto the noun, so
// word order is free in a way English's is not. Greek is broadly SVO like
// English but also has cases, so it too can move words around for emphasis
// without losing the sense; its articles change shape with gender and case.

const KGEStories = [

// ---------------------------------------------------------------- tier 1: a
// couple of sentences.

{
    id: 'good-morning', title: 'Good Morning', level: 1,
    blurb: 'The first thing you will ever need to say.',
    lines: [
        {
            en: 'Good morning.',
            kn: { text: 'ಶುಭೋದಯ.', tr: 'śubhōdaya', say: 'shu-BHOH-da-ya' },
            el: { text: 'Καλημέρα.', tr: 'Kaliméra.', say: 'ka-lee-MEH-ra' },
            gloss: [['Good', 'śubha — auspicious', 'kali- — good'],
                    ['morning', 'udaya — rising', 'méra — day']],
            note: 'Neither language says "morning". Kannada joins śubha (auspicious) to udaya (the sun\'s rising) — the a+u collides and becomes ō, which is why it is śubhōdaya and not śubha-udaya. Greek says "good day" and means it until about noon.'
        },
        {
            en: 'How are you?',
            kn: { text: 'ಹೇಗಿದ್ದೀರಿ?', tr: 'hēgiddīri?', say: 'HEH-gid-DEE-ree' },
            el: { text: 'Τι κάνεις;', tr: 'Ti káneis?', say: 'tee KA-nees' },
            gloss: [['How', 'hēge — how', 'ti — what'],
                    ['are you', 'iddīri — you (polite) are', 'káneis — you do']],
            note: 'Greek asks "what are you doing?" and expects "fine", not an itinerary. Note the Greek question mark: it is a semicolon, ";". Kannada -īri is the polite plural ending; to a child or a close friend you would say hēgiddīya.'
        }
    ]
},

{
    id: 'the-cat', title: 'The Cat on the Wall', level: 1,
    blurb: 'Two sentences, three word orders.',
    lines: [
        {
            en: 'The cat is sleeping on the wall.',
            kn: { text: 'ಬೆಕ್ಕು ಗೋಡೆಯ ಮೇಲೆ ಮಲಗಿದೆ.', tr: 'bekku gōḍeya mēle malagide', say: 'BEK-ku GOH-de-ya MEH-le ma-la-GI-de' },
            el: { text: 'Η γάτα κοιμάται στον τοίχο.', tr: 'I gáta koimátai ston tícho.', say: 'ee GHA-ta kee-MA-teh ston TEE-kho' },
            gloss: [['the cat', 'bekku', 'i gáta'],
                    ['on the wall', 'gōḍeya mēle', 'ston tícho'],
                    ['is sleeping', 'malagide', 'koimátai']],
            note: 'Watch the verb move. English puts it second, Kannada puts it dead last, Greek keeps it second like English. Kannada has no word for "the" at all — bekku is cat, the cat, a cat, whichever the context wants. Greek insists on the article: i is "the" for a feminine noun, and gáta is feminine.'
        },
        {
            en: 'It is not afraid of the dog.',
            kn: { text: 'ಅದು ನಾಯಿಗೆ ಹೆದರುವುದಿಲ್ಲ.', tr: 'adu nāyige hedaruvudilla', say: 'a-DU NAA-yi-ge he-da-ru-vu-DIL-la' },
            el: { text: 'Δεν φοβάται τον σκύλο.', tr: 'Den fovátai ton skýlo.', say: 'then fo-VA-teh ton SKEE-lo' },
            gloss: [['it', 'adu', '(carried in the verb)'],
                    ['the dog', 'nāyige — to the dog', 'ton skýlo'],
                    ['is not afraid', 'hedaruvudilla', 'den fovátai']],
            note: 'Kannada is afraid *to* the dog: -ge is the dative ending, and fear takes it. The negative -illa is glued on the end of the verb rather than standing in front of it. Greek drops the pronoun entirely — fovátai already says "he/she/it fears" — and puts den before the verb. Greek δ is the "th" of *this*, not of *thin*.'
        }
    ]
},

{
    id: 'rain', title: 'Rain', level: 1,
    blurb: 'Weather, and a verb with no subject.',
    lines: [
        {
            en: 'It is raining.',
            kn: { text: 'ಮಳೆ ಬರುತ್ತಿದೆ.', tr: 'maḷe baruttide', say: 'MA-ḷe ba-rut-TI-de' },
            el: { text: 'Βρέχει.', tr: 'Vréchei.', say: 'VREH-khee' },
            gloss: [['rain', 'maḷe', '(inside the verb)'],
                    ['is coming / falls', 'baruttide', 'vréchei']],
            note: 'English needs a fake subject — "it" is not anything. Greek needs nothing at all: vréchei is one word and a complete sentence. Kannada says the rain is *coming*, which is how it feels. The ḷ in maḷe is a retroflex l: curl the tongue back and touch the roof of the mouth.'
        },
        {
            en: 'Come inside, the tea is ready.',
            kn: { text: 'ಒಳಗೆ ಬನ್ನಿ, ಚಹಾ ಸಿದ್ಧವಾಗಿದೆ.', tr: 'oḷage banni, cahā siddhavāgide', say: 'O-ḷa-ge BAN-ni, cha-HAA sid-dha-VAA-gi-de' },
            el: { text: 'Έλα μέσα, το τσάι είναι έτοιμο.', tr: 'Éla mésa, to tsái eínai étoimo.', say: 'EH-la MEH-sa, to TSAH-ee EE-neh EH-tee-mo' },
            gloss: [['come', 'banni (polite)', 'éla (familiar)'],
                    ['inside', 'oḷage', 'mésa'],
                    ['the tea', 'cahā', 'to tsái'],
                    ['is ready', 'siddhavāgide', 'eínai étoimo']],
            note: 'Both languages put "inside" before the verb of motion, the opposite of English. Kannada banni is the polite imperative — to one friend you would say bā. Greek to is the neuter article; tsái is neuter, so "ready" must be neuter too, hence étoimo rather than étoimos or étoimi. Adjectives in Greek always agree.'
        }
    ]
},

// ---------------------------------------------------------------- tier 2:
// four sentences.

{
    id: 'market', title: 'At the Market', level: 2,
    blurb: 'Buying vegetables, and asking what things cost.',
    lines: [
        {
            en: 'I am going to the market.',
            kn: { text: 'ನಾನು ಮಾರುಕಟ್ಟೆಗೆ ಹೋಗುತ್ತಿದ್ದೇನೆ.', tr: 'nānu mārukaṭṭege hōguttiddēne', say: 'NAA-nu MAA-ru-kaṭ-ṭe-ge HOH-gut-tid-DEH-ne' },
            el: { text: 'Πηγαίνω στην αγορά.', tr: 'Pigaíno stin agorá.', say: 'pee-YEH-no steen a-gho-RA' },
            gloss: [['I', 'nānu', '(in the verb)'],
                    ['to the market', 'mārukaṭṭege', 'stin agorá'],
                    ['am going', 'hōguttiddēne', 'pigaíno']],
            note: 'The Greek agorá is the same word as the ancient marketplace, and stin is a fusion of se (to) with tin (the, feminine accusative). Kannada glues -ge onto the noun to mean "to". Kannada verbs carry the person too — -ēne is "I" — so nānu is optional and often dropped.'
        },
        {
            en: 'How much are the tomatoes?',
            kn: { text: 'ಟೊಮ್ಯಾಟೊ ಎಷ್ಟು?', tr: 'ṭomyāṭo eṣṭu?', say: 'ṭo-MYAA-ṭo ESH-ṭu' },
            el: { text: 'Πόσο κάνουν οι ντομάτες;', tr: 'Póso kánoun oi ntomátes?', say: 'PO-so KA-noon ee do-MA-tes' },
            gloss: [['how much', 'eṣṭu', 'póso'],
                    ['the tomatoes', 'ṭomyāṭo', 'oi ntomátes'],
                    ['are (cost)', '(understood)', 'kánoun — they do']],
            note: 'Kannada leaves the verb out entirely: "tomatoes how-much?" is a whole question. Greek asks what they *do*, the same verb as in "how are you". Greek ντ at the start of a word is pronounced d — ntomátes is do-MA-tes.'
        },
        {
            en: 'Thirty rupees a kilo.',
            kn: { text: 'ಕಿಲೋಗೆ ಮೂವತ್ತು ರೂಪಾಯಿ.', tr: 'kilōge mūvattu rūpāyi', say: 'ki-LOH-ge MOO-vat-tu ROO-paa-yi' },
            el: { text: 'Δύο ευρώ το κιλό.', tr: 'Dýo evró to kiló.', say: 'THEE-o ev-RO to kee-LO' },
            gloss: [['thirty / two', 'mūvattu', 'dýo'],
                    ['rupees / euro', 'rūpāyi', 'evró'],
                    ['a kilo', 'kilōge — to a kilo', 'to kiló — the kilo']],
            note: 'The same dative -ge does "per": kilōge is "per kilo". Greek uses the plain article instead, to kiló, which is how English once said "a shilling the pound". Note evró never changes shape — it is one of a handful of Greek nouns that refuse to decline.'
        },
        {
            en: 'That is too expensive. Give me half a kilo.',
            kn: { text: 'ಅದು ತುಂಬಾ ದುಬಾರಿ. ಅರ್ಧ ಕಿಲೋ ಕೊಡಿ.', tr: 'adu tumbā dubāri. ardha kilō koḍi', say: 'a-DU tum-BAA du-BAA-ri. AR-dha ki-LOH KO-ḍi' },
            el: { text: 'Είναι πολύ ακριβό. Δώσε μου μισό κιλό.', tr: 'Eínai polý akrivó. Dóse mou misó kiló.', say: 'EE-neh po-LEE a-kree-VO. THO-se moo mee-SO kee-LO' },
            gloss: [['too / very', 'tumbā', 'polý'],
                    ['expensive', 'dubāri', 'akrivó'],
                    ['give', 'koḍi', 'dóse'],
                    ['me', '(understood)', 'mou'],
                    ['half a kilo', 'ardha kilō', 'misó kiló']],
            note: 'Kannada does not need "to me" — koḍi to a person in front of you can only mean give it here. Greek hangs mou (to me) after the verb as an unstressed little word that never takes the accent. Both languages put the amount before the thing, as English does.'
        }
    ]
},

{
    id: 'my-family', title: 'My Family', level: 2,
    blurb: 'Possession, which the two languages build in opposite directions.',
    lines: [
        {
            en: 'This is my mother.',
            kn: { text: 'ಇವರು ನನ್ನ ಅಮ್ಮ.', tr: 'ivaru nanna amma', say: 'i-va-RU NAN-na AM-ma' },
            el: { text: 'Αυτή είναι η μητέρα μου.', tr: 'Aftí eínai i mitéra mou.', say: 'af-TEE EE-neh ee mee-TEH-ra moo' },
            gloss: [['this (person)', 'ivaru', 'aftí'],
                    ['my', 'nanna — before', 'mou — after'],
                    ['mother', 'amma', 'i mitéra']],
            note: 'The possessive lands on opposite sides: Kannada nanna amma is "my mother" in English order, Greek i mitéra mou is "the mother of-me". Kannada ivaru is a plural form used for one person out of respect — you would use it for an elder and adu for a thing.'
        },
        {
            en: 'My father is a teacher.',
            kn: { text: 'ನನ್ನ ತಂದೆ ಶಿಕ್ಷಕರು.', tr: 'nanna tande śikṣakaru', say: 'NAN-na TAN-de SHIK-sha-ka-ru' },
            el: { text: 'Ο πατέρας μου είναι δάσκαλος.', tr: 'O patéras mou eínai dáskalos.', say: 'o pa-TEH-ras moo EE-neh THA-ska-los' },
            gloss: [['my father', 'nanna tande', 'o patéras mou'],
                    ['is', '(none)', 'eínai'],
                    ['a teacher', 'śikṣakaru', 'dáskalos']],
            note: 'Kannada has no verb "to be" in this kind of sentence — two nouns side by side simply are each other. Greek needs eínai. Greek also drops the article before a job: dáskalos, not o dáskalos, exactly where English drops it too but says "a".'
        },
        {
            en: 'I have two sisters and one brother.',
            kn: { text: 'ನನಗೆ ಇಬ್ಬರು ಅಕ್ಕ-ತಂಗಿಯರು ಮತ್ತು ಒಬ್ಬ ಅಣ್ಣ ಇದ್ದಾರೆ.', tr: 'nanage ibbaru akka-tangiyaru mattu obba aṇṇa iddāre', say: 'na-na-GE IB-ba-ru AK-ka-TAN-gi-ya-ru mat-TU OB-ba AṆ-ṇa id-DAA-re' },
            el: { text: 'Έχω δύο αδελφές και έναν αδελφό.', tr: 'Écho dýo adelfés kai énan adelfó.', say: 'EH-kho THEE-o a-thel-FES keh EH-nan a-thel-FO' },
            gloss: [['I have', 'nanage ... iddāre — to me they are', 'écho'],
                    ['two sisters', 'ibbaru akka-tangiyaru', 'dýo adelfés'],
                    ['and', 'mattu', 'kai'],
                    ['one brother', 'obba aṇṇa', 'énan adelfó']],
            note: 'Kannada has no verb "to have". It says "to me there are two sisters" — nanage is "to me" and iddāre is "they exist". Kannada also has no single word for sister: akka is an elder sister, tangi a younger one, and the pair together means sisters in general. The same is true of aṇṇa (elder brother) and tamma (younger).'
        },
        {
            en: 'We live in a small house near the river.',
            kn: { text: 'ನಾವು ನದಿಯ ಹತ್ತಿರ ಸಣ್ಣ ಮನೆಯಲ್ಲಿ ವಾಸಿಸುತ್ತೇವೆ.', tr: 'nāvu nadiya hattira saṇṇa maneyalli vāsisuttēve', say: 'NAA-vu NA-di-ya HAT-ti-ra SAṆ-ṇa MA-ne-yal-li vaa-si-sut-TEH-ve' },
            el: { text: 'Μένουμε σε ένα μικρό σπίτι κοντά στο ποτάμι.', tr: 'Ménoume se éna mikró spíti kontá sto potámi.', say: 'MEH-noo-meh se EH-na mee-KRO SPEE-tee kon-DA sto po-TA-mee' },
            gloss: [['we live', 'nāvu vāsisuttēve', 'ménoume'],
                    ['in a small house', 'saṇṇa maneyalli', 'se éna mikró spíti'],
                    ['near the river', 'nadiya hattira', 'kontá sto potámi']],
            note: 'Now the orders come apart. English and Greek run house-then-river; Kannada runs river-then-house-then-verb, because everything piles up in front of the verb and the verb ends the sentence. Kannada -alli is "in", glued on: mane (house) becomes maneyalli (in the house).'
        }
    ]
},

{
    id: 'coffee', title: 'Coffee', level: 2,
    blurb: 'Ordering, and the polite forms both languages reach for.',
    lines: [
        {
            en: 'One coffee, please.',
            kn: { text: 'ಒಂದು ಕಾಫಿ ಕೊಡಿ, ದಯವಿಟ್ಟು.', tr: 'ondu kāphi koḍi, dayaviṭṭu', say: 'ON-du KAA-phi KO-ḍi, DA-ya-viṭ-ṭu' },
            el: { text: 'Έναν καφέ, παρακαλώ.', tr: 'Énan kafé, parakaló.', say: 'EH-nan ka-FEH, pa-ra-ka-LO' },
            gloss: [['one', 'ondu', 'énan'],
                    ['coffee', 'kāphi', 'kafé'],
                    ['please', 'dayaviṭṭu', 'parakaló']],
            note: 'Greek énan rather than énas because the coffee is the object of an unspoken "I want" — the accusative shows even with the verb missing. Kannada dayaviṭṭu is literally "having placed kindness" and is a little formal; in a café most people would just say the polite verb koḍi and smile.'
        },
        {
            en: 'With milk or without?',
            kn: { text: 'ಹಾಲಿನೊಂದಿಗೆ ಅಥವಾ ಇಲ್ಲದೆ?', tr: 'hālinondige athavā illade?', say: 'HAA-li-non-di-ge a-tha-VAA IL-la-de' },
            el: { text: 'Με γάλα ή χωρίς;', tr: 'Me gála í chorís?', say: 'meh GHA-la ee kho-REES' },
            gloss: [['with milk', 'hālinondige', 'me gála'],
                    ['or', 'athavā', 'í'],
                    ['without', 'illade', 'chorís']],
            note: '"With" is another ending in Kannada — -ondige — bolted onto hālu (milk), which softens to hālin- before it. Greek keeps me as a separate word. Greek χ is a rasp at the back of the throat, like the ch in Scottish *loch*.'
        },
        {
            en: 'Sit down. I will bring it to you.',
            kn: { text: 'ಕುಳಿತುಕೊಳ್ಳಿ. ನಾನು ತಂದುಕೊಡುತ್ತೇನೆ.', tr: 'kuḷitukoḷḷi. nānu tandukoḍuttēne', say: 'ku-ḷi-tu-KOḶ-ḷi. NAA-nu tan-du-ko-ḍut-TEH-ne' },
            el: { text: 'Καθίστε. Θα σας το φέρω.', tr: 'Kathíste. Tha sas to féro.', say: 'ka-THEE-steh. tha sas to FEH-ro' },
            gloss: [['sit down', 'kuḷitukoḷḷi', 'kathíste'],
                    ['I will bring', 'tandukoḍuttēne', 'tha féro'],
                    ['it to you', '(understood)', 'sas to']],
            note: 'Greek builds the future with tha in front of the present — tha féro, "I will bring". The little words stack in a fixed order before the verb: tha sas to féro is will-to-you-it-I-bring. Kannada compounds two verbs, tandu (having brought) and koḍu (give), into one word meaning bring-and-hand-over.'
        },
        {
            en: 'Thank you very much.',
            kn: { text: 'ತುಂಬಾ ಧನ್ಯವಾದಗಳು.', tr: 'tumbā dhanyavādagaḷu', say: 'tum-BAA DHAN-ya-VAA-da-ga-ḷu' },
            el: { text: 'Ευχαριστώ πολύ.', tr: 'Efcharistó polý.', say: 'ef-kha-ree-STO po-LEE' },
            gloss: [['very much', 'tumbā', 'polý'],
                    ['thanks', 'dhanyavādagaḷu', 'efcharistó']],
            note: 'Kannada puts the "very" first, Greek puts it last. Kannada dhanyavādagaḷu is a plural noun — "thanks", literally "blessed-words" — while Greek efcharistó is a verb, "I thank". The English word *eucharist* is the same root.'
        }
    ]
},

// ---------------------------------------------------------------- tier 3:
// seven sentences.

{
    id: 'bus-to-mysore', title: 'The Bus to Mysore', level: 3,
    blurb: 'A journey, a mistake, and a kind stranger.',
    lines: [
        { en: 'The bus leaves at six in the morning.',
          kn: { text: 'ಬಸ್ಸು ಬೆಳಿಗ್ಗೆ ಆರು ಗಂಟೆಗೆ ಹೊರಡುತ್ತದೆ.', tr: 'bassu beḷigge āru gaṇṭege horaḍuttade', say: 'BAS-su be-ḶIG-ge AA-ru gaṇ-ṭe-GE ho-ra-ḍut-TA-de' },
          el: { text: 'Το λεωφορείο φεύγει στις έξι το πρωί.', tr: 'To leoforeío févgei stis éxi to proí.', say: 'to leh-o-fo-REE-o FEV-yee stees EK-see to pro-EE' },
          gloss: [['the bus','bassu','to leoforeío'],['at six','āru gaṇṭege','stis éxi'],['in the morning','beḷigge','to proí'],['leaves','horaḍuttade','févgei']],
          note: 'Kannada marks the hour with the same dative -ge: gaṇṭege is "at the hour". Greek stis is "at the" feminine plural, agreeing with an unspoken óres (hours).' },
        { en: 'I arrived late and the seats were full.',
          kn: { text: 'ನಾನು ತಡವಾಗಿ ಬಂದೆ ಮತ್ತು ಸೀಟುಗಳು ತುಂಬಿದ್ದವು.', tr: 'nānu taḍavāgi bande mattu sīṭugaḷu tumbiddavu', say: 'NAA-nu ta-ḍa-VAA-gi BAN-de mat-TU SEE-ṭu-ga-ḷu tum-BID-da-vu' },
          el: { text: 'Έφτασα αργά και οι θέσεις ήταν γεμάτες.', tr: 'Éftasa argá kai oi théseis ítan gemátes.', say: 'EF-ta-sa ar-GHA keh ee THEH-sees EE-tan yeh-MA-tes' },
          gloss: [['I arrived','bande','éftasa'],['late','taḍavāgi','argá'],['the seats','sīṭugaḷu','oi théseis'],['were full','tumbiddavu','ítan gemátes']],
          note: 'Kannada makes adverbs by adding -āgi: taḍa (delay) becomes taḍavāgi (lately). Greek gemátes is feminine plural to match théseis — the adjective follows the noun it describes wherever the noun goes.' },
        { en: 'An old woman moved her bag.',
          kn: { text: 'ಒಬ್ಬ ವೃದ್ಧ ಮಹಿಳೆ ತನ್ನ ಚೀಲವನ್ನು ಸರಿಸಿದರು.', tr: 'obba vr̥ddha mahiḷe tanna cīlavannu sarisidaru', say: 'OB-ba VRID-dha ma-HI-ḷe TAN-na CHEE-la-van-nu sa-ri-SI-da-ru' },
          el: { text: 'Μια ηλικιωμένη κυρία μετακίνησε την τσάντα της.', tr: 'Mia ilikioméni kyría metakínise tin tsánta tis.', say: 'mya ee-lee-kee-o-MEH-nee kee-REE-a me-ta-KEE-nee-se teen TSAN-da tees' },
          gloss: [['an old woman','obba vr̥ddha mahiḷe','mia ilikioméni kyría'],['her bag','tanna cīlavannu','tin tsánta tis'],['moved','sarisidaru','metakínise']],
          note: 'The -annu ending on cīla marks it as the thing being acted on — the accusative. Kannada uses it for definite objects and drops it for vague ones. The verb takes the respectful plural -daru because she is an elder.' },
        { en: 'She told me to sit beside her.',
          kn: { text: 'ಅವರು ನನಗೆ ತಮ್ಮ ಪಕ್ಕದಲ್ಲಿ ಕುಳಿತುಕೊಳ್ಳಲು ಹೇಳಿದರು.', tr: 'avaru nanage tamma pakkadalli kuḷitukoḷḷalu hēḷidaru', say: 'a-va-RU na-na-GE TAM-ma PAK-ka-dal-li ku-ḷi-tu-KOḶ-ḷa-lu HEH-ḷi-da-ru' },
          el: { text: 'Μου είπε να καθίσω δίπλα της.', tr: 'Mou eípe na kathíso dípla tis.', say: 'moo EE-peh na ka-THEE-so THEE-pla tees' },
          gloss: [['to me','nanage','mou'],['beside her','tamma pakkadalli','dípla tis'],['to sit','kuḷitukoḷḷalu','na kathíso'],['she told','hēḷidaru','eípe']],
          note: 'Greek has no infinitive. Where English says "to sit", Greek says na kathíso — "that I may sit" — fully conjugated. Kannada uses a real infinitive ending, -alu.' },
        { en: 'We talked about her village for two hours.',
          kn: { text: 'ನಾವು ಎರಡು ಗಂಟೆ ಅವರ ಹಳ್ಳಿಯ ಬಗ್ಗೆ ಮಾತನಾಡಿದೆವು.', tr: 'nāvu eraḍu gaṇṭe avara haḷḷiya bagge mātanāḍidevu', say: 'NAA-vu E-ra-ḍu GAṆ-ṭe A-va-ra HAḶ-ḷi-ya BAG-ge maa-ta-NAA-ḍi-de-vu' },
          el: { text: 'Μιλήσαμε για το χωριό της δύο ώρες.', tr: 'Milísame gia to chorió tis dýo óres.', say: 'mee-LEE-sa-meh ya to kho-RYO tees THEE-o O-res' },
          gloss: [['we talked','mātanāḍidevu','milísame'],['about her village','avara haḷḷiya bagge','gia to chorió tis'],['for two hours','eraḍu gaṇṭe','dýo óres']],
          note: 'Neither language needs a word for "for" with a stretch of time — the bare phrase does it. Kannada bagge (about) comes after its noun, like every Kannada postposition.' },
        { en: 'She gave me a banana and would not take money.',
          kn: { text: 'ಅವರು ನನಗೆ ಬಾಳೆಹಣ್ಣು ಕೊಟ್ಟರು ಮತ್ತು ಹಣ ತೆಗೆದುಕೊಳ್ಳಲಿಲ್ಲ.', tr: 'avaru nanage bāḷehaṇṇu koṭṭaru mattu haṇa tegedukoḷḷalilla', say: 'a-va-RU na-na-GE BAA-ḷe-haṇ-ṇu KOṬ-ṭa-ru mat-TU HA-ṇa te-ge-du-koḶ-ḷa-LIL-la' },
          el: { text: 'Μου έδωσε μια μπανάνα και δεν πήρε λεφτά.', tr: 'Mou édose mia banána kai den píre leftá.', say: 'moo EH-tho-se mya ba-NA-na keh then PEE-re lef-TA' },
          gloss: [['to me','nanage','mou'],['a banana','bāḷehaṇṇu','mia banána'],['gave','koṭṭaru','édose'],['money','haṇa','leftá'],['did not take','tegedukoḷḷalilla','den píre']],
          note: 'Greek μπ at the start of a word is b — banána. The negative den sits before the verb; Kannada -illa is welded onto the end of it.' },
        { en: 'I still think about her sometimes.',
          kn: { text: 'ನಾನು ಈಗಲೂ ಕೆಲವೊಮ್ಮೆ ಅವರ ಬಗ್ಗೆ ಯೋಚಿಸುತ್ತೇನೆ.', tr: 'nānu īgalū kelavomme avara bagge yōcisuttēne', say: 'NAA-nu EE-ga-loo KE-la-vom-me A-va-ra BAG-ge yoh-chi-sut-TEH-ne' },
          el: { text: 'Ακόμα τη σκέφτομαι μερικές φορές.', tr: 'Akóma ti skéftomai merikés forés.', say: 'a-KO-ma tee SKEF-to-meh me-ree-KES fo-RES' },
          gloss: [['still','īgalū','akóma'],['sometimes','kelavomme','merikés forés'],['about her','avara bagge','ti — her'],['I think','yōcisuttēne','skéftomai']],
          note: 'Greek skéftomai looks passive and is not — a whole class of Greek verbs ends in -omai while meaning something perfectly active. Kannada īgalū is īga (now) plus the "even/also" particle -ū: even now.' }
    ]
},

{
    id: 'island-cafe', title: 'The Island Café', level: 3,
    blurb: 'An afternoon that does not go anywhere, pleasantly.',
    lines: [
        { en: 'The café is beside the sea.',
          kn: { text: 'ಕೆಫೆ ಸಮುದ್ರದ ಪಕ್ಕದಲ್ಲಿದೆ.', tr: 'kephe samudrada pakkadallide', say: 'KE-phe sa-MU-dra-da PAK-ka-dal-li-de' },
          el: { text: 'Το καφενείο είναι δίπλα στη θάλασσα.', tr: 'To kafeneío eínai dípla sti thálassa.', say: 'to ka-fe-NEE-o EE-neh THEE-pla stee THA-la-sa' },
          gloss: [['the café','kephe','to kafeneío'],['beside the sea','samudrada pakkadalli','dípla sti thálassa'],['is','-ide','eínai']],
          note: 'Kannada builds a chain of endings: samudra + -da (of) + pakka (side) + -alli (in) + ide (is). Greek θ is the th of *thin*, unvoiced.' },
        { en: 'An old man is playing backgammon alone.',
          kn: { text: 'ಒಬ್ಬ ವೃದ್ಧರು ಒಬ್ಬರೇ ಆಟ ಆಡುತ್ತಿದ್ದಾರೆ.', tr: 'obba vr̥ddharu obbarē āṭa āḍuttiddāre', say: 'OB-ba VRID-dha-ru ob-ba-REH AA-ṭa aa-ḍut-tid-DAA-re' },
          el: { text: 'Ένας γέρος παίζει τάβλι μόνος του.', tr: 'Énas géros paízei távli mónos tou.', say: 'EH-nas YEH-ros PEH-zee TAV-lee MO-nos too' },
          gloss: [['an old man','obba vr̥ddharu','énas géros'],['alone','obbarē','mónos tou'],['is playing','āḍuttiddāre','paízei'],['backgammon','āṭa — a game','távli']],
          note: 'Greek mónos tou is "alone of-him" and changes with the person: a woman would be móni tis. The -ē on obbarē is an emphatic particle: one, and only one.' },
        { en: 'The waiter brings water without being asked.',
          kn: { text: 'ಕೇಳದೆಯೇ ಮಾಣಿ ನೀರು ತರುತ್ತಾರೆ.', tr: 'kēḷadeyē māṇi nīru taruttāre', say: 'KEH-ḷa-de-yeh MAA-ṇi NEE-ru ta-rut-TAA-re' },
          el: { text: 'Ο σερβιτόρος φέρνει νερό χωρίς να του ζητήσεις.', tr: 'O servitóros férnei neró chorís na tou zitíseis.', say: 'o ser-vee-TO-ros FER-nee ne-RO kho-REES na too zee-TEE-sees' },
          gloss: [['the waiter','māṇi','o servitóros'],['water','nīru','neró'],['brings','taruttāre','férnei'],['without asking','kēḷadeyē','chorís na tou zitíseis']],
          note: 'Kannada compresses the whole clause into one word: kēḷ- (ask) + -ade (without) + -yē (even). Greek needs five words for the same idea.' },
        { en: 'The light on the water is very bright.',
          kn: { text: 'ನೀರಿನ ಮೇಲಿನ ಬೆಳಕು ತುಂಬಾ ಪ್ರಕಾಶಮಾನವಾಗಿದೆ.', tr: 'nīrina mēlina beḷaku tumbā prakāśamānavāgide', say: 'NEE-ri-na MEH-li-na BE-ḷa-ku tum-BAA pra-KAA-sha-MAA-na-vaa-GI-de' },
          el: { text: 'Το φως πάνω στο νερό είναι πολύ δυνατό.', tr: 'To fos páno sto neró eínai polý dynató.', say: 'to fos PA-no sto ne-RO EE-neh po-LEE thee-na-TO' },
          gloss: [['the light','beḷaku','to fos'],['on the water','nīrina mēlina','páno sto neró'],['very bright','tumbā prakāśamānavāgide','polý dynató']],
          note: 'Greek dynató literally means strong — Greek describes light as strong rather than bright. Note the Kannada -ina ending turning "on top" into an adjective: mēlina beḷaku, the light that is on top.' },
        { en: 'Nobody is in a hurry here.',
          kn: { text: 'ಇಲ್ಲಿ ಯಾರಿಗೂ ಆತುರವಿಲ್ಲ.', tr: 'illi yārigū āturavilla', say: 'IL-li YAA-ri-goo AA-tu-ra-VIL-la' },
          el: { text: 'Κανείς δεν βιάζεται εδώ.', tr: 'Kaneís den viázetai edó.', say: 'ka-NEES then vee-A-ze-teh e-THO' },
          gloss: [['here','illi','edó'],['nobody','yārigū','kaneís den'],['is in a hurry','āturavilla','viázetai']],
          note: 'Greek doubles the negative and must: kaneís (nobody) still needs den. Kannada says "to nobody is there hurry" — yāru (who) plus -ge (to) plus -ū (even) makes "to anyone at all".' },
        { en: 'I order a second coffee and open my book.',
          kn: { text: 'ನಾನು ಎರಡನೇ ಕಾಫಿ ಹೇಳಿ ನನ್ನ ಪುಸ್ತಕ ತೆರೆಯುತ್ತೇನೆ.', tr: 'nānu eraḍanē kāphi hēḷi nanna pustaka tereyuttēne', say: 'NAA-nu e-ra-ḍa-NEH KAA-phi HEH-ḷi NAN-na PU-sta-ka te-re-yut-TEH-ne' },
          el: { text: 'Παραγγέλνω δεύτερο καφέ και ανοίγω το βιβλίο μου.', tr: 'Parangélno déftero kafé kai anoígo to vivlío mou.', say: 'pa-ran-GEL-no THEF-te-ro ka-FEH keh a-NEE-gho to vee-VLEE-o moo' },
          gloss: [['a second coffee','eraḍanē kāphi','déftero kafé'],['I order','hēḷi — having said','parangélno'],['my book','nanna pustaka','to vivlío mou'],['I open','tereyuttēne','anoígo']],
          note: 'Kannada strings actions with a participle: hēḷi is "having ordered", and only the last verb takes a full ending. A Kannada paragraph can run on for a long time before it finds its main verb.' },
        { en: 'The afternoon passes and I do not mind.',
          kn: { text: 'ಮಧ್ಯಾಹ್ನ ಕಳೆಯುತ್ತದೆ ಮತ್ತು ನನಗೆ ಬೇಸರವಿಲ್ಲ.', tr: 'madhyāhna kaḷeyuttade mattu nanage bēsaravilla', say: 'ma-DHYAAH-na ka-ḷe-yut-TA-de mat-TU na-na-GE BEH-sa-ra-VIL-la' },
          el: { text: 'Το απόγευμα περνάει και δεν με πειράζει.', tr: 'To apógevma pernáei kai den me peirázei.', say: 'to a-PO-yev-ma per-NA-ee keh then me pee-RA-zee' },
          gloss: [['the afternoon','madhyāhna','to apógevma'],['passes','kaḷeyuttade','pernáei'],['I do not mind','nanage bēsaravilla','den me peirázei']],
          note: 'Both languages turn the feeling around: Greek says "it does not bother me", Kannada says "to me there is no annoyance". English is unusual in making the person the subject of minding.' }
    ]
},

{
    id: 'lost-key', title: 'The Lost Key', level: 3,
    blurb: 'A small domestic catastrophe.',
    lines: [
        { en: 'I cannot find my key.',
          kn: { text: 'ನನಗೆ ನನ್ನ ಕೀಲಿ ಸಿಗುತ್ತಿಲ್ಲ.', tr: 'nanage nanna kīli siguttilla', say: 'na-na-GE NAN-na KEE-li si-gut-TIL-la' },
          el: { text: 'Δεν βρίσκω το κλειδί μου.', tr: 'Den vrísko to kleidí mou.', say: 'then VREE-sko to klee-THEE moo' },
          gloss: [['my key','nanna kīli','to kleidí mou'],['I cannot find','nanage siguttilla','den vrísko']],
          note: 'Kannada does not say "I find" — it says the key is-not-being-got to me. The finder is in the dative and the thing found is the subject.' },
        { en: 'Did you look in your coat?',
          kn: { text: 'ನಿಮ್ಮ ಕೋಟಿನಲ್ಲಿ ನೋಡಿದಿರಾ?', tr: 'nimma kōṭinalli nōḍidirā?', say: 'NIM-ma KOH-ṭi-nal-li NOH-ḍi-di-RAA' },
          el: { text: 'Κοίταξες στο παλτό σου;', tr: 'Koítaxes sto paltó sou?', say: 'KEE-ta-kses sto pal-TO soo' },
          gloss: [['in your coat','nimma kōṭinalli','sto paltó sou'],['did you look','nōḍidirā','koítaxes']],
          note: 'Kannada turns a statement into a question by adding -ā to the verb — nothing else moves. Greek does it with intonation alone, and the ";" on the page.' },
        { en: 'It was not there. I looked twice.',
          kn: { text: 'ಅಲ್ಲಿ ಇರಲಿಲ್ಲ. ನಾನು ಎರಡು ಬಾರಿ ನೋಡಿದೆ.', tr: 'alli iralilla. nānu eraḍu bāri nōḍide', say: 'AL-li i-ra-LIL-la. NAA-nu E-ra-ḍu BAA-ri NOH-ḍi-de' },
          el: { text: 'Δεν ήταν εκεί. Κοίταξα δύο φορές.', tr: 'Den ítan ekeí. Koítaxa dýo forés.', say: 'then EE-tan e-KEE. KEE-ta-ksa THEE-o fo-RES' },
          gloss: [['there','alli','ekeí'],['it was not','iralilla','den ítan'],['twice','eraḍu bāri','dýo forés']],
          note: 'Kannada iralilla is the past of "to be", negated: ir- (be) + -al- + -illa. The negative is a suffix in Kannada and a separate word in Greek, every single time.' },
        { en: 'Perhaps you left it in the door.',
          kn: { text: 'ಬಹುಶಃ ನೀವು ಅದನ್ನು ಬಾಗಿಲಲ್ಲಿ ಬಿಟ್ಟಿರಬಹುದು.', tr: 'bahuśaḥ nīvu adannu bāgilalli biṭṭirabahudu', say: 'ba-hu-SHAH NEE-vu a-DAN-nu BAA-gi-lal-li biṭ-ṭi-ra-BA-hu-du' },
          el: { text: 'Ίσως το άφησες στην πόρτα.', tr: 'Ísos to áfises stin pórta.', say: 'EE-sos to A-fee-ses steen POR-ta' },
          gloss: [['perhaps','bahuśaḥ','ísos'],['it','adannu','to'],['in the door','bāgilalli','stin pórta'],['you left','biṭṭirabahudu','áfises']],
          note: 'Kannada carries the "maybe" twice — once in bahuśaḥ and again in the verb ending -bahudu, which means "it is possible that". Greek is content with ísos.' },
        { en: 'You are right. Here it is.',
          kn: { text: 'ನೀವು ಸರಿಯಾಗಿ ಹೇಳಿದಿರಿ. ಇಲ್ಲಿದೆ.', tr: 'nīvu sariyāgi hēḷidiri. illide', say: 'NEE-vu sa-ri-YAA-gi HEH-ḷi-di-ri. IL-li-de' },
          el: { text: 'Έχεις δίκιο. Να το.', tr: 'Écheis díkio. Na to.', say: 'EH-khees THEE-kyo. na to' },
          gloss: [['you are right','nīvu sariyāgi hēḷidiri','écheis díkio — you have right'],['here it is','illide','na to']],
          note: 'Greek *has* right rather than *is* right, as French and Spanish do. Na to is the Greek way of pointing at something — "there it is", handed over in two syllables.' },
        { en: 'I have been looking for an hour.',
          kn: { text: 'ನಾನು ಒಂದು ಗಂಟೆಯಿಂದ ಹುಡುಕುತ್ತಿದ್ದೇನೆ.', tr: 'nānu ondu gaṇṭeyinda huḍukuttiddēne', say: 'NAA-nu ON-du GAṆ-ṭe-yin-da hu-ḍu-kut-tid-DEH-ne' },
          el: { text: 'Ψάχνω μία ώρα.', tr: 'Psáchno mía óra.', say: 'PSAKH-no MEE-a O-ra' },
          gloss: [['for an hour','ondu gaṇṭeyinda — since an hour','mía óra'],['I have been looking','huḍukuttiddēne','psáchno']],
          note: 'Greek uses the plain present for something still going on — psáchno mía óra, "I search one hour", means I have been at it an hour and still am. Kannada marks the starting point with -inda, "since".' },
        { en: 'Next time, put it in the same place.',
          kn: { text: 'ಮುಂದಿನ ಸಲ ಅದೇ ಜಾಗದಲ್ಲಿ ಇಡಿ.', tr: 'mundina sala adē jāgadalli iḍi', say: 'MUN-di-na SA-la a-DEH JAA-ga-dal-li I-ḍi' },
          el: { text: 'Την επόμενη φορά, βάλ\' το στο ίδιο μέρος.', tr: 'Tin epómeni forá, vál\' to sto ídio méros.', say: 'teen e-PO-me-nee fo-RA, VAL to sto EE-thyo MEH-ros' },
          gloss: [['next time','mundina sala','tin epómeni forá'],['in the same place','adē jāgadalli','sto ídio méros'],['put it','iḍi','vál\' to']],
          note: 'Greek clips vále to vál\' before another vowel-ish sound, the way English says "gonna". The apostrophe is written. Kannada adē is adu (that) plus the emphatic -ē: that very one.' }
    ]
},

// ---------------------------------------------------------------- tier 4:
// ten sentences.

{
    id: 'grandmother-garden', title: 'Grandmother’s Garden', level: 4,
    blurb: 'A place remembered, and the past tense.',
    lines: [
        { en: 'My grandmother had a small garden behind the house.',
          kn: { text: 'ನನ್ನ ಅಜ್ಜಿಗೆ ಮನೆಯ ಹಿಂದೆ ಸಣ್ಣ ತೋಟವಿತ್ತು.', tr: 'nanna ajjige maneya hinde saṇṇa tōṭavittu', say: 'NAN-na AJ-ji-ge MA-ne-ya HIN-de SAṆ-ṇa TOH-ṭa-VIT-tu' },
          el: { text: 'Η γιαγιά μου είχε έναν μικρό κήπο πίσω από το σπίτι.', tr: 'I giagiá mou eíche énan mikró kípo píso apó to spíti.', say: 'ee ya-YA moo EE-khe EH-nan mee-KRO KEE-po PEE-so a-PO to SPEE-tee' },
          gloss: [['my grandmother','nanna ajjige — to my grandmother','i giagiá mou'],['a small garden','saṇṇa tōṭa','énan mikró kípo'],['behind the house','maneya hinde','píso apó to spíti'],['had','-ittu — there was','eíche']],
          note: 'Kannada still has no "have": to-my-grandmother a-garden was. Greek eíche is the past of écho. Note Greek needs apó after píso — "behind from the house".' },
        { en: 'She grew tomatoes, chillies and one lemon tree.',
          kn: { text: 'ಅವರು ಟೊಮ್ಯಾಟೊ, ಮೆಣಸಿನಕಾಯಿ ಮತ್ತು ಒಂದು ನಿಂಬೆ ಮರ ಬೆಳೆಸಿದರು.', tr: 'avaru ṭomyāṭo, meṇasinakāyi mattu ondu nimbe mara beḷesidaru', say: 'a-va-RU ṭo-MYAA-ṭo, me-ṇa-si-na-KAA-yi mat-TU ON-du NIM-be MA-ra be-ḷe-SI-da-ru' },
          el: { text: 'Καλλιεργούσε ντομάτες, πιπεριές και μια λεμονιά.', tr: 'Kalliergoúse ntomátes, piperiés kai mia lemoniá.', say: 'ka-lyer-GHOO-se do-MA-tes, pee-per-YES keh mya le-mo-NYA' },
          gloss: [['she grew','beḷesidaru','kalliergoúse'],['tomatoes','ṭomyāṭo','ntomátes'],['chillies','meṇasinakāyi','piperiés'],['a lemon tree','nimbe mara','mia lemoniá']],
          note: 'Greek has one word for a lemon *tree*, lemoniá, distinct from the fruit lemóni — most fruit trees work this way. Kannada builds it from two words, nimbe (lemon) and mara (tree).' },
        { en: 'Every morning she watered them before the sun rose.',
          kn: { text: 'ಪ್ರತಿ ಬೆಳಿಗ್ಗೆ ಸೂರ್ಯ ಏಳುವ ಮೊದಲು ಅವರು ನೀರು ಹಾಕುತ್ತಿದ್ದರು.', tr: 'prati beḷigge sūrya ēḷuva modalu avaru nīru hākuttiddaru', say: 'PRA-ti be-ḶIG-ge SOOR-ya EH-ḷu-va MO-da-lu a-va-RU NEE-ru haa-kut-TID-da-ru' },
          el: { text: 'Κάθε πρωί τα πότιζε πριν βγει ο ήλιος.', tr: 'Káthe proí ta pótize prin vgei o ílios.', say: 'KA-the pro-EE ta PO-tee-ze preen vyee o EE-lyos' },
          gloss: [['every morning','prati beḷigge','káthe proí'],['before the sun rose','sūrya ēḷuva modalu','prin vgei o ílios'],['she watered them','nīru hākuttiddaru','ta pótize']],
          note: 'Both languages put the time clause before the verb. Kannada modalu (before) comes after the thing it refers to, as all its postpositions do.' },
        { en: 'I was small and the plants were taller than me.',
          kn: { text: 'ನಾನು ಚಿಕ್ಕವನಾಗಿದ್ದೆ ಮತ್ತು ಗಿಡಗಳು ನನಗಿಂತ ಎತ್ತರವಾಗಿದ್ದವು.', tr: 'nānu cikkavanāgidde mattu giḍagaḷu nanaginta ettaravāgiddavu', say: 'NAA-nu CHIK-ka-va-naa-GID-de mat-TU GI-ḍa-ga-ḷu na-na-GIN-ta ET-ta-ra-vaa-GID-da-vu' },
          el: { text: 'Ήμουν μικρός και τα φυτά ήταν πιο ψηλά από μένα.', tr: 'Ímoun mikrós kai ta fytá ítan pio psilá apó ména.', say: 'EE-moon mee-KROS keh ta fee-TA EE-tan pyo psee-LA a-PO MEH-na' },
          gloss: [['I was small','nānu cikkavanāgidde','ímoun mikrós'],['the plants','giḍagaḷu','ta fytá'],['taller than me','nanaginta ettaravāgiddavu','pio psilá apó ména']],
          note: 'Kannada compares with -inta glued to the thing compared: nanaginta is "than me". Greek uses pio (more) plus apó (from), the same shape as French *plus... que*.' },
        { en: 'She told me the names of everything.',
          kn: { text: 'ಅವರು ನನಗೆ ಎಲ್ಲದರ ಹೆಸರುಗಳನ್ನು ಹೇಳಿದರು.', tr: 'avaru nanage elladara hesarugaḷannu hēḷidaru', say: 'a-va-RU na-na-GE EL-la-da-ra HE-sa-ru-ga-ḷan-nu HEH-ḷi-da-ru' },
          el: { text: 'Μου έλεγε τα ονόματα των πάντων.', tr: 'Mou élege ta onómata ton pánton.', say: 'moo EH-le-yeh ta o-NO-ma-ta ton PAN-don' },
          gloss: [['to me','nanage','mou'],['the names','hesarugaḷannu','ta onómata'],['of everything','elladara','ton pánton'],['she told','hēḷidaru','élege']],
          note: 'Greek ton pánton is a genitive plural — "of all things". Kannada does the same job with -a on ellada: elladara, of everything.' },
        { en: 'I have forgotten most of them.',
          kn: { text: 'ನಾನು ಅವುಗಳಲ್ಲಿ ಹೆಚ್ಚಿನವನ್ನು ಮರೆತಿದ್ದೇನೆ.', tr: 'nānu avugaḷalli heccinavannu maretiddēne', say: 'NAA-nu A-vu-ga-ḷal-li HECH-chi-na-van-nu ma-re-tid-DEH-ne' },
          el: { text: 'Έχω ξεχάσει τα περισσότερα.', tr: 'Écho xechásei ta perissótera.', say: 'EH-kho kse-KHA-see ta pe-ree-SO-te-ra' },
          gloss: [['most of them','avugaḷalli heccinavannu','ta perissótera'],['I have forgotten','maretiddēne','écho xechásei']],
          note: 'Greek builds the perfect exactly as English does: écho (have) plus an unchanging form of the verb. Kannada folds it into one word ending in -iddēne.' },
        { en: 'But I remember the smell of the leaves.',
          kn: { text: 'ಆದರೆ ಎಲೆಗಳ ವಾಸನೆ ನನಗೆ ನೆನಪಿದೆ.', tr: 'ādare elegaḷa vāsane nanage nenapide', say: 'AA-da-re E-le-ga-ḷa VAA-sa-ne na-na-GE NE-na-pi-de' },
          el: { text: 'Αλλά θυμάμαι τη μυρωδιά των φύλλων.', tr: 'Allá thymámai ti myrodiá ton fýllon.', say: 'a-LA thee-MA-meh tee mee-ro-THYA ton FEE-lon' },
          gloss: [['but','ādare','allá'],['the smell of the leaves','elegaḷa vāsane','ti myrodiá ton fýllon'],['I remember','nanage nenapide — to me there is memory','thymámai']],
          note: 'Kannada turns it round again: the memory exists, and it exists *to me*. This dative-subject pattern covers most feelings, needs and knowing in Kannada.' },
        { en: 'The house was sold after she died.',
          kn: { text: 'ಅವರು ತೀರಿಕೊಂಡ ನಂತರ ಮನೆಯನ್ನು ಮಾರಲಾಯಿತು.', tr: 'avaru tīrikoṇḍa nantara maneyannu māralāyitu', say: 'a-va-RU TEE-ri-koṇ-ḍa NAN-ta-ra MA-ne-yan-nu maa-ra-LAA-yi-tu' },
          el: { text: 'Το σπίτι πουλήθηκε αφού πέθανε.', tr: 'To spíti poulíthike afoú péthane.', say: 'to SPEE-tee poo-LEE-thee-ke a-FOO PEH-tha-ne' },
          gloss: [['after she died','avaru tīrikoṇḍa nantara','afoú péthane'],['the house','maneyannu','to spíti'],['was sold','māralāyitu','poulíthike']],
          note: 'Both languages have a real passive. Greek poulíthike is one word doing what English needs three for. Kannada tīrikoḷḷu is the gentle verb for dying, as English says "passed away".' },
        { en: 'Someone else lives there now.',
          kn: { text: 'ಈಗ ಅಲ್ಲಿ ಬೇರೆ ಯಾರೋ ವಾಸಿಸುತ್ತಾರೆ.', tr: 'īga alli bēre yārō vāsisuttāre', say: 'EE-ga AL-li BEH-re YAA-roh vaa-si-sut-TAA-re' },
          el: { text: 'Τώρα μένει κάποιος άλλος εκεί.', tr: 'Tóra ménei kápoios állos ekeí.', say: 'TO-ra MEH-nee KA-pyos A-los e-KEE' },
          gloss: [['now','īga','tóra'],['someone else','bēre yārō','kápoios állos'],['lives there','alli vāsisuttāre','ménei ekeí']],
          note: 'Kannada yārō is yāru (who) plus -ō, which turns a question word into a vague one: who becomes someone. Greek reverses the English order — "someone other" rather than "other someone".' },
        { en: 'I hope they kept the lemon tree.',
          kn: { text: 'ಅವರು ನಿಂಬೆ ಮರವನ್ನು ಉಳಿಸಿಕೊಂಡಿದ್ದಾರೆ ಎಂದು ಆಶಿಸುತ್ತೇನೆ.', tr: 'avaru nimbe maravannu uḷisikoṇḍiddāre endu āśisuttēne', say: 'a-va-RU NIM-be MA-ra-van-nu u-ḷi-si-koṇ-ḍid-DAA-re EN-du aa-shi-sut-TEH-ne' },
          el: { text: 'Ελπίζω να κράτησαν τη λεμονιά.', tr: 'Elpízo na krátisan ti lemoniá.', say: 'el-PEE-zo na KRA-tee-san tee le-mo-NYA' },
          gloss: [['I hope','āśisuttēne','elpízo'],['that they kept','uḷisikoṇḍiddāre endu','na krátisan'],['the lemon tree','nimbe maravannu','ti lemoniá']],
          note: 'Kannada quotes the hoped-for thing first and then labels it with endu, "thus" — the whole clause comes before the verb of hoping. Greek uses na, its all-purpose subordinator.' },
    ]
},

{
    id: 'fisherman', title: 'The Fisherman of Aegina', level: 4,
    blurb: 'Work before dawn, and a good day.',
    lines: [
        { en: 'The harbour is quiet at four in the morning.',
          kn: { text: 'ಬೆಳಿಗ್ಗೆ ನಾಲ್ಕು ಗಂಟೆಗೆ ಬಂದರು ಶಾಂತವಾಗಿರುತ್ತದೆ.', tr: 'beḷigge nālku gaṇṭege bandaru śāntavāgiruttade', say: 'be-ḶIG-ge NAAL-ku gaṇ-ṭe-GE BAN-da-ru SHAAN-ta-vaa-gi-rut-TA-de' },
          el: { text: 'Το λιμάνι είναι ήσυχο στις τέσσερις το πρωί.', tr: 'To limáni eínai ísycho stis tésseris to proí.', say: 'to lee-MA-nee EE-neh EE-see-kho stees TE-se-rees to pro-EE' },
          gloss: [['the harbour','bandaru','to limáni'],['at four','nālku gaṇṭege','stis tésseris'],['is quiet','śāntavāgiruttade','eínai ísycho']],
          note: 'Kannada -āgiruttade is a habitual "is generally": the harbour is quiet as a rule, not just now.' },
        { en: 'He unties the boat and starts the engine.',
          kn: { text: 'ಅವನು ದೋಣಿಯನ್ನು ಬಿಚ್ಚಿ ಎಂಜಿನ್ ಪ್ರಾರಂಭಿಸುತ್ತಾನೆ.', tr: 'avanu dōṇiyannu bicci enjin prārambhisuttāne', say: 'a-va-NU DOH-ṇi-yan-nu BICH-chi EN-jin praa-ram-bhi-sut-TAA-ne' },
          el: { text: 'Λύνει τη βάρκα και βάζει μπροστά τη μηχανή.', tr: 'Lýnei ti várka kai vázei brostá ti michaní.', say: 'LEE-nee tee VAR-ka keh VA-zee bro-STA tee mee-kha-NEE' },
          gloss: [['he unties','bicci — having untied','lýnei'],['the boat','dōṇiyannu','ti várka'],['starts the engine','enjin prārambhisuttāne','vázei brostá ti michaní']],
          note: 'Greek says it "puts the engine forward". Kannada uses avanu (he) for a man of no particular seniority; for an elder it would be avaru, the plural of respect.' },
        { en: 'The sea is flat and black.',
          kn: { text: 'ಸಮುದ್ರ ಸಮತಟ್ಟಾಗಿ ಕಪ್ಪಾಗಿದೆ.', tr: 'samudra samataṭṭāgi kappāgide', say: 'sa-MU-dra sa-ma-taṭ-ṬAA-gi kap-PAA-gi-de' },
          el: { text: 'Η θάλασσα είναι λεία και μαύρη.', tr: 'I thálassa eínai leía kai mávri.', say: 'ee THA-la-sa EE-neh LEE-a keh MAV-ree' },
          gloss: [['the sea','samudra','i thálassa'],['flat','samataṭṭāgi','leía'],['black','kappāgide','mávri']],
          note: 'Both Greek adjectives take feminine endings because thálassa is feminine — leía and mávri, not leíos and mávros.' },
        { en: 'He has fished here for forty years.',
          kn: { text: 'ಅವನು ಇಲ್ಲಿ ನಲವತ್ತು ವರ್ಷಗಳಿಂದ ಮೀನು ಹಿಡಿಯುತ್ತಿದ್ದಾನೆ.', tr: 'avanu illi nalavattu varṣagaḷinda mīnu hiḍiyuttiddāne', say: 'a-va-NU IL-li NA-la-vat-tu VAR-sha-ga-ḷin-da MEE-nu hi-ḍi-yut-tid-DAA-ne' },
          el: { text: 'Ψαρεύει εδώ σαράντα χρόνια.', tr: 'Psarévei edó saránta chrónia.', say: 'psa-REH-vee e-THO sa-RAN-da KHRO-nya' },
          gloss: [['here','illi','edó'],['for forty years','nalavattu varṣagaḷinda','saránta chrónia'],['he has fished','mīnu hiḍiyuttiddāne','psarévei']],
          note: 'Again Greek uses the plain present for something still true. Kannada -inda marks the point it started from.' },
        { en: 'His father did the same work.',
          kn: { text: 'ಅವನ ತಂದೆಯೂ ಇದೇ ಕೆಲಸ ಮಾಡುತ್ತಿದ್ದರು.', tr: 'avana tandeyū idē kelasa māḍuttiddaru', say: 'A-va-na TAN-de-yoo i-DEH KE-la-sa maa-ḍut-TID-da-ru' },
          el: { text: 'Ο πατέρας του έκανε την ίδια δουλειά.', tr: 'O patéras tou ékane tin ídia douleiá.', say: 'o pa-TEH-ras too EH-ka-ne teen EE-thya thoo-LYA' },
          gloss: [['his father','avana tande','o patéras tou'],['the same work','idē kelasa','tin ídia douleiá'],['did','māḍuttiddaru','ékane']],
          note: 'The -yū on tandeyū means "too" — his father also. Kannada carries "also" as a suffix rather than a separate word.' },
        { en: 'Today the nets are heavy.',
          kn: { text: 'ಇಂದು ಬಲೆಗಳು ಭಾರವಾಗಿವೆ.', tr: 'indu balegaḷu bhāravāgive', say: 'IN-du BA-le-ga-ḷu BHAA-ra-vaa-gi-ve' },
          el: { text: 'Σήμερα τα δίχτυα είναι βαριά.', tr: 'Símera ta díchtya eínai variá.', say: 'SEE-me-ra ta THEEKH-tya EE-neh var-YA' },
          gloss: [['today','indu','símera'],['the nets','balegaḷu','ta díchtya'],['are heavy','bhāravāgive','eínai variá']],
          note: 'Kannada -ive is the plural "are" for non-human things; people take -iddāre. The language sorts its verbs by what kind of thing the subject is.' },
        { en: 'He sells the fish at the market by seven.',
          kn: { text: 'ಅವನು ಏಳು ಗಂಟೆಯೊಳಗೆ ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಮೀನು ಮಾರುತ್ತಾನೆ.', tr: 'avanu ēḷu gaṇṭeyoḷage mārukaṭṭeyalli mīnu māruttāne', say: 'a-va-NU EH-ḷu GAṆ-ṭe-yo-ḷa-ge MAA-ru-kaṭ-ṭe-yal-li MEE-nu maa-rut-TAA-ne' },
          el: { text: 'Πουλάει τα ψάρια στην αγορά μέχρι τις εφτά.', tr: 'Pouláei ta psária stin agorá méchri tis eftá.', say: 'poo-LA-ee ta PSA-rya steen a-gho-RA MEH-khree tees ef-TA' },
          gloss: [['by seven','ēḷu gaṇṭeyoḷage','méchri tis eftá'],['at the market','mārukaṭṭeyalli','stin agorá'],['the fish','mīnu','ta psária'],['he sells','māruttāne','pouláei']],
          note: 'Kannada oḷage means "within" — within seven o’clock. Notice the Kannada verb waiting at the very end while Greek got there in word three.' },
        { en: 'Then he drinks a coffee and reads the paper.',
          kn: { text: 'ನಂತರ ಅವನು ಕಾಫಿ ಕುಡಿದು ಪತ್ರಿಕೆ ಓದುತ್ತಾನೆ.', tr: 'nantara avanu kāphi kuḍidu patrike ōduttāne', say: 'NAN-ta-ra a-va-NU KAA-phi ku-ḌI-du PA-tri-ke oh-dut-TAA-ne' },
          el: { text: 'Μετά πίνει έναν καφέ και διαβάζει την εφημερίδα.', tr: 'Metá pínei énan kafé kai diavázei tin efimerída.', say: 'me-TA PEE-nee EH-nan ka-FEH keh thya-VA-zee teen e-fee-me-REE-tha' },
          gloss: [['then','nantara','metá'],['drinks a coffee','kāphi kuḍidu','pínei énan kafé'],['reads the paper','patrike ōduttāne','diavázei tin efimerída']],
          note: 'Kannada kuḍidu is again the "having done" participle chaining two actions under one final verb.' },
        { en: 'In the afternoon he sleeps.',
          kn: { text: 'ಮಧ್ಯಾಹ್ನ ಅವನು ಮಲಗುತ್ತಾನೆ.', tr: 'madhyāhna avanu malaguttāne', say: 'ma-DHYAAH-na a-va-NU ma-la-gut-TAA-ne' },
          el: { text: 'Το απόγευμα κοιμάται.', tr: 'To apógevma koimátai.', say: 'to a-PO-yev-ma kee-MA-teh' },
          gloss: [['in the afternoon','madhyāhna','to apógevma'],['he sleeps','malaguttāne','koimátai']],
          note: 'Greek marks "in the afternoon" with nothing but the article — to apógevma. The bare accusative does duty as a time expression.' },
        { en: 'It is a hard life and he would not change it.',
          kn: { text: 'ಇದು ಕಷ್ಟದ ಜೀವನ ಆದರೆ ಅವನು ಅದನ್ನು ಬದಲಾಯಿಸುವುದಿಲ್ಲ.', tr: 'idu kaṣṭada jīvana ādare avanu adannu badalāyisuvudilla', say: 'i-DU KASH-ṭa-da JEE-va-na AA-da-re a-va-NU a-DAN-nu ba-da-laa-yi-su-vu-DIL-la' },
          el: { text: 'Είναι δύσκολη ζωή αλλά δεν θα την άλλαζε.', tr: 'Eínai dýskoli zoí allá den tha tin állaze.', say: 'EE-neh THEE-sko-lee zo-EE a-LA then tha teen A-la-ze' },
          gloss: [['a hard life','kaṣṭada jīvana','dýskoli zoí'],['but','ādare','allá'],['he would not change it','adannu badalāyisuvudilla','den tha tin állaze']],
          note: 'Greek makes the conditional with tha plus a past tense — tha állaze, "he would change". Kannada leans on the plain negative future.' },
    ]
},

{
    id: 'festival-lights', title: 'The Festival of Lights', level: 4,
    blurb: 'Deepavali in one house, and the vocabulary of celebration.',
    lines: [
        { en: 'Tomorrow is the festival.',
          kn: { text: 'ನಾಳೆ ಹಬ್ಬ.', tr: 'nāḷe habba', say: 'NAA-ḷe HAB-ba' },
          el: { text: 'Αύριο είναι η γιορτή.', tr: 'Ávrio eínai i giortí.', say: 'AV-ryo EE-neh ee yor-TEE' },
          gloss: [['tomorrow','nāḷe','ávrio'],['the festival','habba','i giortí'],['is','(none)','eínai']],
          note: 'Two words is a whole Kannada sentence. Greek cannot drop eínai the way Kannada drops its copula.' },
        { en: 'My mother is making sweets since morning.',
          kn: { text: 'ನನ್ನ ಅಮ್ಮ ಬೆಳಿಗ್ಗೆಯಿಂದ ಸಿಹಿ ಮಾಡುತ್ತಿದ್ದಾರೆ.', tr: 'nanna amma beḷiggeyinda sihi māḍuttiddāre', say: 'NAN-na AM-ma be-ḶIG-ge-yin-da SI-hi maa-ḍut-tid-DAA-re' },
          el: { text: 'Η μητέρα μου φτιάχνει γλυκά από το πρωί.', tr: 'I mitéra mou ftiáchnei glyká apó to proí.', say: 'ee mee-TEH-ra moo FTYAKH-nee ghlee-KA a-PO to pro-EE' },
          gloss: [['my mother','nanna amma','i mitéra mou'],['since morning','beḷiggeyinda','apó to proí'],['is making sweets','sihi māḍuttiddāre','ftiáchnei glyká']],
          note: 'Kannada -inda and Greek apó do the same job here: from/since a point in time.' },
        { en: 'We clean the whole house.',
          kn: { text: 'ನಾವು ಇಡೀ ಮನೆಯನ್ನು ಸ್ವಚ್ಛಗೊಳಿಸುತ್ತೇವೆ.', tr: 'nāvu iḍī maneyannu svacchagoḷisuttēve', say: 'NAA-vu i-ḌEE MA-ne-yan-nu SVACH-cha-go-ḷi-sut-TEH-ve' },
          el: { text: 'Καθαρίζουμε όλο το σπίτι.', tr: 'Katharízoume ólo to spíti.', say: 'ka-tha-REE-zoo-meh O-lo to SPEE-tee' },
          gloss: [['we clean','svacchagoḷisuttēve','katharízoume'],['the whole house','iḍī maneyannu','ólo to spíti']],
          note: 'Kannada -goḷisu turns an adjective into "make it so": svacchagoḷisu is literally to make-clean.' },
        { en: 'My father buys oil for the lamps.',
          kn: { text: 'ನನ್ನ ತಂದೆ ದೀಪಗಳಿಗೆ ಎಣ್ಣೆ ತರುತ್ತಾರೆ.', tr: 'nanna tande dīpagaḷige eṇṇe taruttāre', say: 'NAN-na TAN-de DEE-pa-ga-ḷi-ge EṆ-ṇe ta-rut-TAA-re' },
          el: { text: 'Ο πατέρας μου αγοράζει λάδι για τα λυχνάρια.', tr: 'O patéras mou agorázei ládi gia ta lychnária.', say: 'o pa-TEH-ras moo a-gho-RA-zee LA-thee ya ta leekh-NA-rya' },
          gloss: [['oil','eṇṇe','ládi'],['for the lamps','dīpagaḷige','gia ta lychnária'],['buys','taruttāre','agorázei']],
          note: 'The dative -ge covers "for" as well as "to". Greek needs the separate word gia.' },
        { en: 'In the evening we light them one by one.',
          kn: { text: 'ಸಂಜೆ ನಾವು ಅವುಗಳನ್ನು ಒಂದೊಂದಾಗಿ ಹಚ್ಚುತ್ತೇವೆ.', tr: 'sañje nāvu avugaḷannu ondondāgi haccuttēve', say: 'SAÑ-je NAA-vu A-vu-ga-ḷan-nu on-don-DAA-gi hach-chut-TEH-ve' },
          el: { text: 'Το βράδυ τα ανάβουμε ένα ένα.', tr: 'To vrády ta anávoume éna éna.', say: 'to VRA-thee ta a-NA-voo-meh EH-na EH-na' },
          gloss: [['in the evening','sañje','to vrády'],['one by one','ondondāgi','éna éna'],['we light them','avugaḷannu haccuttēve','ta anávoume']],
          note: 'Both languages say "one one" and mean one by one, simply by repeating the word.' },
        { en: 'The children are not allowed near the fireworks.',
          kn: { text: 'ಮಕ್ಕಳನ್ನು ಪಟಾಕಿಗಳ ಹತ್ತಿರ ಬಿಡುವುದಿಲ್ಲ.', tr: 'makkaḷannu paṭākigaḷa hattira biḍuvudilla', say: 'MAK-ka-ḷan-nu pa-ṬAA-ki-ga-ḷa HAT-ti-ra bi-ḍu-vu-DIL-la' },
          el: { text: 'Τα παιδιά δεν επιτρέπεται να πλησιάσουν τα πυροτεχνήματα.', tr: 'Ta paidiá den epitrépetai na plisiásoun ta pyrotechnímata.', say: 'ta peh-THYA then e-pee-TREH-pe-teh na plee-SYA-soon ta pee-ro-tekh-NEE-ma-ta' },
          gloss: [['the children','makkaḷannu','ta paidiá'],['near the fireworks','paṭākigaḷa hattira','na plisiásoun ta pyrotechnímata'],['are not allowed','biḍuvudilla','den epitrépetai']],
          note: 'Kannada says plainly "we do not release the children near". Greek uses an impersonal den epitrépetai, "it is not permitted".' },
        { en: 'My grandfather tells the same story every year.',
          kn: { text: 'ನನ್ನ ಅಜ್ಜ ಪ್ರತಿ ವರ್ಷ ಅದೇ ಕಥೆ ಹೇಳುತ್ತಾರೆ.', tr: 'nanna ajja prati varṣa adē kathe hēḷuttāre', say: 'NAN-na AJ-ja PRA-ti VAR-sha a-DEH KA-the heh-ḷut-TAA-re' },
          el: { text: 'Ο παππούς μου λέει την ίδια ιστορία κάθε χρόνο.', tr: 'O pappoús mou léei tin ídia istoría káthe chróno.', say: 'o pa-POOS moo LEH-ee teen EE-thya ee-sto-REE-a KA-the KHRO-no' },
          gloss: [['my grandfather','nanna ajja','o pappoús mou'],['the same story','adē kathe','tin ídia istoría'],['every year','prati varṣa','káthe chróno'],['tells','hēḷuttāre','léei']],
          note: 'Kannada puts the time before the object; Greek puts it last. Both are free to move it — this is just the comfortable order.' },
        { en: 'Nobody minds. We like hearing it.',
          kn: { text: 'ಯಾರೂ ಬೇಸರ ಪಡುವುದಿಲ್ಲ. ನಮಗೆ ಕೇಳಲು ಇಷ್ಟ.', tr: 'yārū bēsara paḍuvudilla. namage kēḷalu iṣṭa', say: 'YAA-roo BEH-sa-ra pa-ḍu-vu-DIL-la. na-ma-GE KEH-ḷa-lu ISH-ṭa' },
          el: { text: 'Κανείς δεν ενοχλείται. Μας αρέσει να την ακούμε.', tr: 'Kaneís den enochleítai. Mas arései na tin akoúme.', say: 'ka-NEES then e-no-KHLEE-teh. mas a-REH-see na teen a-KOO-meh' },
          gloss: [['nobody minds','yārū bēsara paḍuvudilla','kaneís den enochleítai'],['we like','namage iṣṭa — to us it is dear','mas arései — to us it pleases'],['hearing it','kēḷalu','na tin akoúme']],
          note: 'Here the two languages agree completely and both differ from English: liking is something that happens *to* you. Kannada namage and Greek mas are both "to us".' },
        { en: 'The house smells of ghee and smoke.',
          kn: { text: 'ಮನೆಯಲ್ಲಿ ತುಪ್ಪ ಮತ್ತು ಹೊಗೆಯ ವಾಸನೆ ಇದೆ.', tr: 'maneyalli tuppa mattu hogeya vāsane ide', say: 'MA-ne-yal-li TUP-pa mat-TU HO-ge-ya VAA-sa-ne I-de' },
          el: { text: 'Το σπίτι μυρίζει βούτυρο και καπνό.', tr: 'To spíti myrízei voútyro kai kapnó.', say: 'to SPEE-tee mee-REE-zee VOO-tee-ro keh kap-NO' },
          gloss: [['the house','maneyalli — in the house','to spíti'],['of ghee and smoke','tuppa mattu hogeya','voútyro kai kapnó'],['smells','vāsane ide — the smell is','myrízei']],
          note: 'Greek makes the house itself do the smelling, with the smell in the bare accusative. Kannada puts the smell in the house.' },
        { en: 'It is my favourite night of the year.',
          kn: { text: 'ಇದು ವರ್ಷದ ನನ್ನ ಅಚ್ಚುಮೆಚ್ಚಿನ ರಾತ್ರಿ.', tr: 'idu varṣada nanna accumeccina rātri', say: 'i-DU VAR-sha-da NAN-na ACH-chu-mech-chi-na RAA-tri' },
          el: { text: 'Είναι η αγαπημένη μου νύχτα της χρονιάς.', tr: 'Eínai i agapiméni mou nýchta tis chroniás.', say: 'EE-neh ee a-gha-pee-MEH-nee moo NEEKH-ta tees khro-NYAS' },
          gloss: [['my favourite','nanna accumeccina','i agapiméni mou'],['night','rātri','nýchta'],['of the year','varṣada','tis chroniás']],
          note: 'Kannada puts "of the year" first, Greek puts it last, and both use a possessive ending rather than a preposition to do it.' },
    ]
},


// ---------------------------------------------------------------- tier 5:
// fourteen sentences, a few pages of reading.

{
    id: 'two-friends', title: 'The Two Friends and the Bear', level: 5,
    blurb: 'A folk tale that exists in both countries, told here in three languages.',
    lines: [
        { en: 'Two friends were walking through a forest.',
          kn: { text: 'ಇಬ್ಬರು ಸ್ನೇಹಿತರು ಕಾಡಿನಲ್ಲಿ ನಡೆದುಕೊಂಡು ಹೋಗುತ್ತಿದ್ದರು.', tr: 'ibbaru snēhitaru kāḍinalli naḍedukoṇḍu hōguttiddaru', say: 'IB-ba-ru SNEH-hi-ta-ru KAA-ḍi-nal-li na-ḍe-du-KOṆ-ḍu hoh-gut-TID-da-ru' },
          el: { text: 'Δύο φίλοι περπατούσαν μέσα σε ένα δάσος.', tr: 'Dýo fíloi perpatoúsan mésa se éna dásos.', say: 'THEE-o FEE-lee per-pa-TOO-san MEH-sa se EH-na THA-sos' },
          gloss: [['two friends','ibbaru snēhitaru','dýo fíloi'],['through a forest','kāḍinalli','mésa se éna dásos'],['were walking','naḍedukoṇḍu hōguttiddaru','perpatoúsan']],
          note: 'Greek -oúsan is the imperfect: they were walking, over a stretch of time, as opposed to perpátisan, they walked and finished.' },
        { en: 'They had promised to help each other.',
          kn: { text: 'ಅವರು ಪರಸ್ಪರ ಸಹಾಯ ಮಾಡುವುದಾಗಿ ಮಾತು ಕೊಟ್ಟಿದ್ದರು.', tr: 'avaru paraspara sahāya māḍuvudāgi mātu koṭṭiddaru', say: 'a-va-RU pa-RA-spa-ra sa-HAA-ya maa-ḍu-vu-DAA-gi MAA-tu koṭ-ṭID-da-ru' },
          el: { text: 'Είχαν υποσχεθεί να βοηθήσει ο ένας τον άλλον.', tr: 'Eíchan yposchetheí na voithísei o énas ton állon.', say: 'EE-khan ee-po-skhe-THEE na vo-ee-THEE-see o EH-nas ton A-lon' },
          gloss: [['they had promised','mātu koṭṭiddaru — had given word','eíchan yposchetheí'],['to help each other','paraspara sahāya māḍuvudāgi','na voithísei o énas ton állon']],
          note: 'Greek says "the one the other" for each other. Kannada has a single word, paraspara. Both build the pluperfect the same way: had + past participle.' },
        { en: 'Suddenly a bear came out of the trees.',
          kn: { text: 'ಇದ್ದಕ್ಕಿದ್ದಂತೆ ಒಂದು ಕರಡಿ ಮರಗಳ ಹಿಂದಿನಿಂದ ಬಂತು.', tr: 'iddakkiddante ondu karaḍi maragaḷa hindininda bantu', say: 'id-dak-kid-DAN-te ON-du KA-ra-ḍi MA-ra-ga-ḷa hin-di-NIN-da BAN-tu' },
          el: { text: 'Ξαφνικά μια αρκούδα βγήκε από τα δέντρα.', tr: 'Xafniká mia arkoúda vgíke apó ta déntra.', say: 'ksaf-nee-KA mya ar-KOO-tha VYEE-ke a-PO ta THEN-dra' },
          gloss: [['suddenly','iddakkiddante','xafniká'],['a bear','ondu karaḍi','mia arkoúda'],['out of the trees','maragaḷa hindininda','apó ta déntra'],['came','bantu','vgíke']],
          note: 'Greek ξ is a single letter for the ks sound. Kannada -ninda is "from", stacked on hindi (behind): from behind the trees.' },
        { en: 'The first friend climbed a tree at once.',
          kn: { text: 'ಮೊದಲನೆಯ ಸ್ನೇಹಿತ ತಕ್ಷಣ ಮರ ಹತ್ತಿದ.', tr: 'modalaneya snēhita takṣaṇa mara hattida', say: 'MO-da-la-ne-ya SNEH-hi-ta TAK-sha-ṇa MA-ra HAT-ti-da' },
          el: { text: 'Ο πρώτος φίλος ανέβηκε αμέσως σε ένα δέντρο.', tr: 'O prótos fílos anévike amésos se éna déntro.', say: 'o PRO-tos FEE-los a-NEH-vee-ke a-MEH-sos se EH-na THEN-dro' },
          gloss: [['the first friend','modalaneya snēhita','o prótos fílos'],['at once','takṣaṇa','amésos'],['climbed a tree','mara hattida','anévike se éna déntro']],
          note: 'Kannada -ida is the plain past for a male subject of no special status; the respectful form would be hattidaru.' },
        { en: 'The second could not climb.',
          kn: { text: 'ಎರಡನೆಯವನಿಗೆ ಹತ್ತಲು ಆಗಲಿಲ್ಲ.', tr: 'eraḍaneyavanige hattalu āgalilla', say: 'e-ra-DA-ne-ya-va-ni-ge HAT-ta-lu AA-ga-LIL-la' },
          el: { text: 'Ο δεύτερος δεν μπορούσε να ανέβει.', tr: 'O défteros den boroúse na anévei.', say: 'o THEF-te-ros then bo-ROO-se na a-NEH-vee' },
          gloss: [['the second','eraḍaneyavanige — to the second','o défteros'],['to climb','hattalu','na anévei'],['could not','āgalilla — it did not become','den boroúse']],
          note: 'Kannada expresses inability as "it did not happen to him" — the person is in the dative and the failure is the subject.' },
        { en: 'So he lay down and held his breath.',
          kn: { text: 'ಆದ್ದರಿಂದ ಅವನು ಮಲಗಿ ಉಸಿರು ಬಿಗಿಹಿಡಿದ.', tr: 'āddarinda avanu malagi usiru bigihiḍida', say: 'AAD-da-rin-da a-va-NU MA-la-gi U-si-ru bi-gi-HI-ḍi-da' },
          el: { text: 'Έτσι ξάπλωσε και κράτησε την ανάσα του.', tr: 'Étsi xáplose kai krátise tin anása tou.', say: 'ET-see KSA-plo-se keh KRA-tee-se teen a-NA-sa too' },
          gloss: [['so','āddarinda','étsi'],['lay down','malagi','xáplose'],['held his breath','usiru bigihiḍida','krátise tin anása tou']],
          note: 'Greek needs tou (of him) to say whose breath; Kannada leaves it out because it could not be anyone else’s.' },
        { en: 'The bear sniffed his ear and walked away.',
          kn: { text: 'ಕರಡಿ ಅವನ ಕಿವಿಯನ್ನು ಮೂಸಿ ಹೊರಟುಹೋಯಿತು.', tr: 'karaḍi avana kiviyannu mūsi horaṭuhōyitu', say: 'KA-ra-ḍi A-va-na KI-vi-yan-nu MOO-si ho-ra-ṭu-HOH-yi-tu' },
          el: { text: 'Η αρκούδα μύρισε το αυτί του και έφυγε.', tr: 'I arkoúda mýrise to aftí tou kai éfyge.', say: 'ee ar-KOO-tha MEE-ree-se to af-TEE too keh EH-fee-ye' },
          gloss: [['the bear','karaḍi','i arkoúda'],['his ear','avana kiviyannu','to aftí tou'],['sniffed','mūsi','mýrise'],['walked away','horaṭuhōyitu','éfyge']],
          note: 'Kannada -yitu is the past for a non-human subject. Bears, rain and buses all take it; people do not.' },
        { en: 'The first friend came down and laughed.',
          kn: { text: 'ಮೊದಲನೆಯವನು ಕೆಳಗಿಳಿದು ನಕ್ಕ.', tr: 'modalaneyavanu keḷagiḷidu nakka', say: 'MO-da-la-ne-ya-va-nu ke-ḷa-GI-ḷi-du NAK-ka' },
          el: { text: 'Ο πρώτος κατέβηκε και γέλασε.', tr: 'O prótos katévike kai gélase.', say: 'o PRO-tos ka-TEH-vee-ke keh YEH-la-se' },
          gloss: [['the first','modalaneyavanu','o prótos'],['came down','keḷagiḷidu','katévike'],['laughed','nakka','gélase']],
          note: 'Greek γ before e or i is a soft y sound: gélase is YEH-la-se, not GEH-la-se.' },
        { en: 'He asked what the bear had whispered.',
          kn: { text: 'ಕರಡಿ ಏನು ಪಿಸುಗುಟ್ಟಿತು ಎಂದು ಕೇಳಿದ.', tr: 'karaḍi ēnu pisuguṭṭitu endu kēḷida', say: 'KA-ra-ḍi EH-nu pi-su-GUṬ-ṭi-tu EN-du KEH-ḷi-da' },
          el: { text: 'Ρώτησε τι ψιθύρισε η αρκούδα.', tr: 'Rótise ti psithýrise i arkoúda.', say: 'RO-tee-se tee psee-THEE-ree-se ee ar-KOO-tha' },
          gloss: [['he asked','kēḷida','rótise'],['what the bear whispered','karaḍi ēnu pisuguṭṭitu endu','ti psithýrise i arkoúda']],
          note: 'The Kannada quote comes first and endu closes it, like a spoken pair of quotation marks. Greek keeps English order.' },
        { en: 'The second friend answered slowly.',
          kn: { text: 'ಎರಡನೆಯವನು ನಿಧಾನವಾಗಿ ಉತ್ತರಿಸಿದ.', tr: 'eraḍaneyavanu nidhānavāgi uttarisida', say: 'e-ra-DA-ne-ya-va-nu ni-DHAA-na-vaa-gi ut-ta-RI-si-da' },
          el: { text: 'Ο δεύτερος απάντησε αργά.', tr: 'O défteros apántise argá.', say: 'o THEF-te-ros a-PAN-dee-se ar-GHA' },
          gloss: [['the second friend','eraḍaneyavanu','o défteros'],['slowly','nidhānavāgi','argá'],['answered','uttarisida','apántise']],
          note: 'Greek ντ inside a word is nd: apántise is a-PAN-dee-se.' },
        { en: '"It told me not to trust a coward."',
          kn: { text: '"ಹೇಡಿಯನ್ನು ನಂಬಬೇಡ ಎಂದು ಹೇಳಿತು."', tr: '"hēḍiyannu nambabēḍa endu hēḷitu"', say: 'HEH-ḍi-yan-nu nam-ba-BEH-ḍa EN-du HEH-ḷi-tu' },
          el: { text: '«Μου είπε να μην εμπιστεύομαι έναν δειλό.»', tr: '«Mou eípe na min empistévomai énan deiló.»', say: 'moo EE-peh na meen em-pee-STEH-vo-meh EH-nan thee-LO' },
          gloss: [['it told me','hēḷitu','mou eípe'],['not to trust','nambabēḍa endu','na min empistévomai'],['a coward','hēḍiyannu','énan deiló']],
          note: 'Kannada -bēḍa is a special negative imperative: do not. Greek negates a na-clause with min rather than den. Greek quotation marks are « ».' },
        { en: 'The first friend said nothing.',
          kn: { text: 'ಮೊದಲನೆಯವನು ಏನೂ ಹೇಳಲಿಲ್ಲ.', tr: 'modalaneyavanu ēnū hēḷalilla', say: 'MO-da-la-ne-ya-va-nu EH-noo heh-ḷa-LIL-la' },
          el: { text: 'Ο πρώτος δεν είπε τίποτα.', tr: 'O prótos den eípe típota.', say: 'o PRO-tos then EE-peh TEE-po-ta' },
          gloss: [['said nothing','ēnū hēḷalilla','den eípe típota'],['the first','modalaneyavanu','o prótos']],
          note: 'Again the Greek double negative: den and típota together. Kannada ēnū is ēnu (what) plus -ū (even): not even what.' },
        { en: 'They walked home without speaking.',
          kn: { text: 'ಅವರು ಮಾತನಾಡದೆ ಮನೆಗೆ ನಡೆದರು.', tr: 'avaru mātanāḍade manege naḍedaru', say: 'a-va-RU maa-ta-NAA-ḍa-de MA-ne-ge NA-ḍe-da-ru' },
          el: { text: 'Περπάτησαν σπίτι χωρίς να μιλήσουν.', tr: 'Perpátisan spíti chorís na milísoun.', say: 'per-PA-tee-san SPEE-tee kho-REES na mee-LEE-soon' },
          gloss: [['they walked','naḍedaru','perpátisan'],['home','manege','spíti'],['without speaking','mātanāḍade','chorís na milísoun']],
          note: 'One Kannada word, mātanāḍade, for the whole English phrase "without speaking": the -ade ending is a negative participle.' },
        { en: 'They were never friends again.',
          kn: { text: 'ಅವರು ಮತ್ತೆ ಎಂದಿಗೂ ಸ್ನೇಹಿತರಾಗಲಿಲ್ಲ.', tr: 'avaru matte endigū snēhitarāgalilla', say: 'a-va-RU MAT-te en-di-GOO SNEH-hi-ta-raa-ga-LIL-la' },
          el: { text: 'Δεν ξαναέγιναν ποτέ φίλοι.', tr: 'Den xanaéginan poté fíloi.', say: 'then ksa-na-EH-yee-nan po-TEH FEE-lee' },
          gloss: [['never again','matte endigū','xana- ... poté'],['friends','snēhitarāgalilla','fíloi'],['they were not','-illa','den éginan']],
          note: 'Greek builds "again" into the verb as the prefix xana-. Kannada endigū is "at any time ever", and needs the negative on the verb to mean never.' },
    ]
},

{
    id: 'merchant-moon', title: 'The Merchant and the Moon', level: 5,
    blurb: 'A long tale about wanting the wrong thing.',
    lines: [
        { en: 'There was once a rich merchant in the town.',
          kn: { text: 'ಒಂದಾನೊಂದು ಕಾಲದಲ್ಲಿ ಊರಿನಲ್ಲಿ ಒಬ್ಬ ಶ್ರೀಮಂತ ವ್ಯಾಪಾರಿ ಇದ್ದ.', tr: 'ondānondu kāladalli ūrinalli obba śrīmanta vyāpāri idda', say: 'on-DAA-non-du KAA-la-dal-li OO-ri-nal-li OB-ba SHREE-man-ta vyaa-PAA-ri ID-da' },
          el: { text: 'Μια φορά κι έναν καιρό ζούσε ένας πλούσιος έμπορος στην πόλη.', tr: 'Mia forá ki énan kairó zoúse énas ploúsios émporos stin póli.', say: 'mya fo-RA kee EH-nan keh-RO ZOO-se EH-nas PLOO-syos EM-po-ros steen PO-lee' },
          gloss: [['once upon a time','ondānondu kāladalli','mia forá ki énan kairó'],['in the town','ūrinalli','stin póli'],['a rich merchant','obba śrīmanta vyāpāri','énas ploúsios émporos'],['there was','idda','zoúse — lived']],
          note: 'Both languages have a fixed formula for opening a tale, and both mean roughly "one time and one season".' },
        { en: 'He owned three ships and forty warehouses.',
          kn: { text: 'ಅವನಿಗೆ ಮೂರು ಹಡಗುಗಳು ಮತ್ತು ನಲವತ್ತು ಉಗ್ರಾಣಗಳಿದ್ದವು.', tr: 'avanige mūru haḍagugaḷu mattu nalavattu ugrāṇagaḷiddavu', say: 'a-va-NI-ge MOO-ru HA-ḍa-gu-ga-ḷu mat-TU NA-la-vat-tu u-GRAA-ṇa-ga-ḷID-da-vu' },
          el: { text: 'Είχε τρία καράβια και σαράντα αποθήκες.', tr: 'Eíche tría karávia kai saránta apothíkes.', say: 'EE-khe TREE-a ka-RA-vya keh sa-RAN-da a-po-THEE-kes' },
          gloss: [['he owned','avanige ... iddavu','eíche'],['three ships','mūru haḍagugaḷu','tría karávia'],['forty warehouses','nalavattu ugrāṇagaḷu','saránta apothíkes']],
          note: 'Greek tría is the neuter form of three, because karávia is neuter; masculine would be treis. Numbers agree in Greek up to four.' },
        { en: 'But every night he sat on the roof and looked at the moon.',
          kn: { text: 'ಆದರೆ ಪ್ರತಿ ರಾತ್ರಿ ಅವನು ಮಾಳಿಗೆಯ ಮೇಲೆ ಕುಳಿತು ಚಂದ್ರನನ್ನು ನೋಡುತ್ತಿದ್ದ.', tr: 'ādare prati rātri avanu māḷigeya mēle kuḷitu candranannu nōḍuttidda', say: 'AA-da-re PRA-ti RAA-tri a-va-NU MAA-ḷi-ge-ya MEH-le ku-ḶI-tu CHAN-dra-nan-nu noh-ḍut-TID-da' },
          el: { text: 'Αλλά κάθε βράδυ καθόταν στη στέγη και κοιτούσε το φεγγάρι.', tr: 'Allá káthe vrády kathótan sti stégi kai koitoúse to fengári.', say: 'a-LA KA-the VRA-thee ka-THO-tan stee STEH-yee keh kee-TOO-se to fen-GA-ree' },
          gloss: [['every night','prati rātri','káthe vrády'],['on the roof','māḷigeya mēle','sti stégi'],['sat','kuḷitu','kathótan'],['looked at the moon','candranannu nōḍuttidda','koitoúse to fengári']],
          note: 'Kannada candra takes -n- before the accusative ending: candranannu. Masculine nouns in -a do this regularly.' },
        { en: '"I want it," he said to his wife.',
          kn: { text: '"ಅದು ನನಗೆ ಬೇಕು" ಎಂದು ಅವನು ಹೆಂಡತಿಗೆ ಹೇಳಿದ.', tr: '"adu nanage bēku" endu avanu heṇḍatige hēḷida', say: 'a-DU na-na-GE BEH-ku EN-du a-va-NU HEṆ-ḍa-ti-ge HEH-ḷi-da' },
          el: { text: '«Το θέλω», είπε στη γυναίκα του.', tr: '«To thélo», eípe sti gynaíka tou.', say: 'to THEH-lo, EE-peh stee yee-NEH-ka too' },
          gloss: [['I want it','adu nanage bēku — to me it is wanted','to thélo'],['he said','hēḷida','eípe'],['to his wife','heṇḍatige','sti gynaíka tou']],
          note: 'Kannada bēku is not a verb but a word meaning "is needed", with the wanter in the dative. Greek thélo is an ordinary verb with an ordinary subject.' },
        { en: 'She told him it was very far away.',
          kn: { text: 'ಅದು ತುಂಬಾ ದೂರ ಇದೆ ಎಂದು ಅವಳು ಹೇಳಿದಳು.', tr: 'adu tumbā dūra ide endu avaḷu hēḷidaḷu', say: 'a-DU tum-BAA DOO-ra I-de EN-du A-va-ḷu HEH-ḷi-da-ḷu' },
          el: { text: 'Του είπε ότι ήταν πολύ μακριά.', tr: 'Tou eípe óti ítan polý makriá.', say: 'too EE-peh O-tee EE-tan po-LEE ma-kree-A' },
          gloss: [['she told him','avaḷu hēḷidaḷu','tou eípe'],['that it was very far','adu tumbā dūra ide endu','óti ítan polý makriá']],
          note: 'Greek óti introduces reported speech, like English "that". Kannada endu does the same job but sits at the end of the quoted part.' },
        { en: 'He did not listen.',
          kn: { text: 'ಅವನು ಕೇಳಲಿಲ್ಲ.', tr: 'avanu kēḷalilla', say: 'a-va-NU keh-ḷa-LIL-la' },
          el: { text: 'Δεν άκουσε.', tr: 'Den ákouse.', say: 'then A-koo-se' },
          gloss: [['he did not listen','kēḷalilla','den ákouse']],
          note: 'Kannada kēḷu means both to hear and to ask; the context decides. Greek keeps them separate: akoúo and rotáo.' },
        { en: 'He sold one ship to buy a long ladder.',
          kn: { text: 'ಉದ್ದನೆಯ ಏಣಿ ಕೊಳ್ಳಲು ಅವನು ಒಂದು ಹಡಗನ್ನು ಮಾರಿದ.', tr: 'uddaneya ēṇi koḷḷalu avanu ondu haḍagannu mārida', say: 'UD-da-ne-ya EH-ṇi KOḶ-ḷa-lu a-va-NU ON-du HA-ḍa-gan-nu MAA-ri-da' },
          el: { text: 'Πούλησε ένα καράβι για να αγοράσει μια μακριά σκάλα.', tr: 'Poúlise éna karávi gia na agorásei mia makriá skála.', say: 'POO-lee-se EH-na ka-RA-vee ya na a-gho-RA-see mya ma-kree-A SKA-la' },
          gloss: [['to buy a long ladder','uddaneya ēṇi koḷḷalu','gia na agorásei mia makriá skála'],['he sold one ship','ondu haḍagannu mārida','poúlise éna karávi']],
          note: 'Kannada puts the purpose clause first, Greek last. Greek marks purpose with gia na — "in order that".' },
        { en: 'The ladder reached the top of the tallest tree.',
          kn: { text: 'ಏಣಿ ಅತಿ ಎತ್ತರದ ಮರದ ತುದಿಯನ್ನು ತಲುಪಿತು.', tr: 'ēṇi ati ettarada marada tudiyannu talupitu', say: 'EH-ṇi A-ti ET-ta-ra-da MA-ra-da TU-di-yan-nu ta-LU-pi-tu' },
          el: { text: 'Η σκάλα έφτασε στην κορυφή του ψηλότερου δέντρου.', tr: 'I skála éftase stin koryfí tou psilóterou déntrou.', say: 'ee SKA-la EF-ta-se steen ko-ree-FEE too psee-LO-te-roo THEN-droo' },
          gloss: [['the ladder','ēṇi','i skála'],['the top of the tallest tree','ati ettarada marada tudiyannu','stin koryfí tou psilóterou déntrou'],['reached','talupitu','éftase']],
          note: 'Greek forms the superlative with -teros plus the article: tou psilóterou, of the taller/tallest. Kannada uses ati (most) in front.' },
        { en: 'The moon was exactly as far away as before.',
          kn: { text: 'ಚಂದ್ರ ಮೊದಲಿನಷ್ಟೇ ದೂರ ಇತ್ತು.', tr: 'candra modalinaṣṭē dūra ittu', say: 'CHAN-dra MO-da-li-nash-ṭEH DOO-ra IT-tu' },
          el: { text: 'Το φεγγάρι ήταν ακριβώς τόσο μακριά όσο πριν.', tr: 'To fengári ítan akrivós tóso makriá óso prin.', say: 'to fen-GA-ree EE-tan a-kree-VOS TO-so ma-kree-A O-so preen' },
          gloss: [['the moon','candra','to fengári'],['exactly as far as before','modalinaṣṭē dūra','akrivós tóso makriá óso prin'],['was','ittu','ítan']],
          note: 'Greek pairs tóso with óso for "as ... as". Kannada does it with one suffix: -aṣṭu (as much as) plus the emphatic -ē.' },
        { en: 'He sold the second ship and built a tower.',
          kn: { text: 'ಅವನು ಎರಡನೆಯ ಹಡಗನ್ನು ಮಾರಿ ಗೋಪುರ ಕಟ್ಟಿಸಿದ.', tr: 'avanu eraḍaneya haḍagannu māri gōpura kaṭṭisida', say: 'a-va-NU e-ra-DA-ne-ya HA-ḍa-gan-nu MAA-ri GOH-pu-ra kaṭ-ṭI-si-da' },
          el: { text: 'Πούλησε το δεύτερο καράβι κι έχτισε έναν πύργο.', tr: 'Poúlise to déftero karávi ki échtise énan pýrgo.', say: 'POO-lee-se to THEF-te-ro ka-RA-vee kee EKH-tee-se EH-nan PEER-gho' },
          gloss: [['sold the second ship','eraḍaneya haḍagannu māri','poúlise to déftero karávi'],['built a tower','gōpura kaṭṭisida','échtise énan pýrgo']],
          note: 'Kannada kaṭṭisida is causative: he had it built rather than laying the bricks himself. The -isu infix does this to almost any verb.' },
        { en: 'From the top he could see the whole sea.',
          kn: { text: 'ಮೇಲಿನಿಂದ ಅವನಿಗೆ ಇಡೀ ಸಮುದ್ರ ಕಾಣುತ್ತಿತ್ತು.', tr: 'mēlininda avanige iḍī samudra kāṇuttittu', say: 'MEH-li-nin-da a-va-NI-ge i-ḌEE sa-MU-dra kaa-ṇut-TIT-tu' },
          el: { text: 'Από την κορυφή έβλεπε όλη τη θάλασσα.', tr: 'Apó tin koryfí évlepe óli ti thálassa.', say: 'a-PO teen ko-ree-FEE EH-vle-peh O-lee tee THA-la-sa' },
          gloss: [['from the top','mēlininda','apó tin koryfí'],['the whole sea','iḍī samudra','óli ti thálassa'],['he could see','avanige kāṇuttittu','évlepe']],
          note: 'Kannada again puts the seer in the dative: to him the sea was visible. Greek keeps him as the subject of an ordinary verb.' },
        { en: 'But the moon had not moved at all.',
          kn: { text: 'ಆದರೆ ಚಂದ್ರ ಸ್ವಲ್ಪವೂ ಚಲಿಸಿರಲಿಲ್ಲ.', tr: 'ādare candra svalpavū calisiralilla', say: 'AA-da-re CHAN-dra SVAL-pa-voo cha-li-si-ra-LIL-la' },
          el: { text: 'Αλλά το φεγγάρι δεν είχε κουνηθεί καθόλου.', tr: 'Allá to fengári den eíche kounitheí kathólou.', say: 'a-LA to fen-GA-ree then EE-khe koo-nee-THEE ka-THO-loo' },
          gloss: [['but','ādare','allá'],['not at all','svalpavū ... -illa','den ... kathólou'],['had moved','calisiralilla','eíche kounitheí']],
          note: 'Kannada svalpavū is "even a little", and like every such word it needs the verb to be negative to mean "not at all".' },
        { en: 'When he sold the third ship his wife left.',
          kn: { text: 'ಮೂರನೆಯ ಹಡಗನ್ನು ಮಾರಿದಾಗ ಅವನ ಹೆಂಡತಿ ಹೊರಟುಹೋದಳು.', tr: 'mūraneya haḍagannu māridāga avana heṇḍati horaṭuhōdaḷu', say: 'MOO-ra-ne-ya HA-ḍa-gan-nu maa-ri-DAA-ga A-va-na HEṆ-ḍa-ti ho-ra-ṭu-HOH-da-ḷu' },
          el: { text: 'Όταν πούλησε το τρίτο καράβι, η γυναίκα του έφυγε.', tr: 'Ótan poúlise to tríto karávi, i gynaíka tou éfyge.', say: 'O-tan POO-lee-se to TREE-to ka-RA-vee, ee yee-NEH-ka too EH-fee-ye' },
          gloss: [['when he sold','māridāga','ótan poúlise'],['the third ship','mūraneya haḍagannu','to tríto karávi'],['his wife left','avana heṇḍati horaṭuhōdaḷu','i gynaíka tou éfyge']],
          note: 'Kannada builds "when" into the verb as -āga. Greek uses the separate word ótan, and keeps English order throughout.' },
        { en: 'He is still on the tower, and the moon is still there.',
          kn: { text: 'ಅವನು ಈಗಲೂ ಗೋಪುರದ ಮೇಲಿದ್ದಾನೆ, ಚಂದ್ರ ಈಗಲೂ ಅಲ್ಲಿಯೇ ಇದ್ದಾನೆ.', tr: 'avanu īgalū gōpurada mēliddāne, candra īgalū alliyē iddāne', say: 'a-va-NU EE-ga-loo GOH-pu-ra-da MEH-lid-DAA-ne, CHAN-dra EE-ga-loo AL-li-yeh id-DAA-ne' },
          el: { text: 'Είναι ακόμα στον πύργο, και το φεγγάρι είναι ακόμα εκεί.', tr: 'Eínai akóma ston pýrgo, kai to fengári eínai akóma ekeí.', say: 'EE-neh a-KO-ma ston PEER-gho, keh to fen-GA-ree EE-neh a-KO-ma e-KEE' },
          gloss: [['still','īgalū','akóma'],['on the tower','gōpurada mēle','ston pýrgo'],['still there','alliyē','akóma ekeí']],
          note: 'Kannada treats the moon as animate here — iddāne, the human form — because in the story he has become a character.' },
    ]
},

{
    id: 'winter-two-countries', title: 'Winter in Two Countries', level: 5,
    blurb: 'The same season, six thousand kilometres apart.',
    lines: [
        { en: 'In Athens the winter is short and wet.',
          kn: { text: 'ಅಥೆನ್ಸ್\u200cನಲ್ಲಿ ಚಳಿಗಾಲ ಚಿಕ್ಕದು ಮತ್ತು ತೇವವಾಗಿರುತ್ತದೆ.', tr: 'athensnalli caḷigāla cikkadu mattu tēvavāgiruttade', say: 'a-THENS-nal-li CHA-ḷi-gaa-la CHIK-ka-du mat-TU TEH-va-vaa-gi-rut-TA-de' },
          el: { text: 'Στην Αθήνα ο χειμώνας είναι σύντομος και βροχερός.', tr: 'Stin Athína o cheimónas eínai sýntomos kai vrocherós.', say: 'steen a-THEE-na o khee-MO-nas EE-neh SEEN-do-mos keh vro-khe-ROS' },
          gloss: [['in Athens','athensnalli','stin Athína'],['the winter','caḷigāla','o cheimónas'],['short and wet','cikkadu mattu tēvavāgiruttade','sýntomos kai vrocherós']],
          note: 'Kannada caḷigāla is caḷi (cold) plus kāla (season) — the cold season, built from parts you already know.' },
        { en: 'It rains for three days and then the sun returns.',
          kn: { text: 'ಮೂರು ದಿನ ಮಳೆ ಬಂದು ನಂತರ ಸೂರ್ಯ ಮತ್ತೆ ಬರುತ್ತಾನೆ.', tr: 'mūru dina maḷe bandu nantara sūrya matte baruttāne', say: 'MOO-ru DI-na MA-ḷe BAN-du NAN-ta-ra SOOR-ya MAT-te ba-rut-TAA-ne' },
          el: { text: 'Βρέχει τρεις μέρες και μετά επιστρέφει ο ήλιος.', tr: 'Vréchei treis méres kai metá epistréfei o ílios.', say: 'VREH-khee trees MEH-res keh me-TA e-pee-STREH-fee o EE-lyos' },
          gloss: [['three days','mūru dina','treis méres'],['it rains','maḷe bandu','vréchei'],['then the sun returns','nantara sūrya matte baruttāne','metá epistréfei o ílios']],
          note: 'Kannada treats the sun as a person — baruttāne, the masculine human ending. Greek gives it the masculine article but an ordinary verb.' },
        { en: 'People still sit outside at midday.',
          kn: { text: 'ಜನರು ಮಧ್ಯಾಹ್ನ ಈಗಲೂ ಹೊರಗೆ ಕುಳಿತುಕೊಳ್ಳುತ್ತಾರೆ.', tr: 'janaru madhyāhna īgalū horage kuḷitukoḷḷuttāre', say: 'JA-na-ru ma-DHYAAH-na EE-ga-loo HO-ra-ge ku-ḷi-tu-koḶ-ḷut-TAA-re' },
          el: { text: 'Ο κόσμος κάθεται ακόμα έξω το μεσημέρι.', tr: 'O kósmos káthetai akóma éxo to mesiméri.', say: 'o KO-smos KA-the-teh a-KO-ma EK-so to me-see-MEH-ree' },
          gloss: [['people','janaru','o kósmos'],['at midday','madhyāhna','to mesiméri'],['still outside','īgalū horage','akóma éxo'],['sit','kuḷitukoḷḷuttāre','káthetai']],
          note: 'Greek o kósmos literally means "the world" and is the everyday word for people in general — it takes a singular verb.' },
        { en: 'In Bangalore there is no winter at all.',
          kn: { text: 'ಬೆಂಗಳೂರಿನಲ್ಲಿ ಚಳಿಗಾಲವೇ ಇಲ್ಲ.', tr: 'bengaḷūrinalli caḷigālavē illa', say: 'ben-ga-ḶOO-ri-nal-li CHA-ḷi-gaa-la-VEH IL-la' },
          el: { text: 'Στη Μπανγκαλόρ δεν υπάρχει καθόλου χειμώνας.', tr: 'Sti Bangalór den ypárchei kathólou cheimónas.', say: 'stee ban-ga-LOR then ee-PAR-khee ka-THO-loo khee-MO-nas' },
          gloss: [['in Bangalore','bengaḷūrinalli','sti Bangalór'],['no winter at all','caḷigālavē illa','den ypárchei kathólou cheimónas']],
          note: 'The emphatic -ē on caḷigālavē is doing the work of "at all". Kannada illa alone is the whole negative verb: there is not.' },
        { en: 'The mornings in December are cool and that is all.',
          kn: { text: 'ಡಿಸೆಂಬರ್\u200cನಲ್ಲಿ ಬೆಳಿಗ್ಗೆ ತಂಪಾಗಿರುತ್ತದೆ, ಅಷ್ಟೇ.', tr: 'ḍisembarnalli beḷigge tampāgiruttade, aṣṭē', say: 'ḍi-SEM-bar-nal-li be-ḶIG-ge tam-PAA-gi-rut-TA-de, ash-ṬEH' },
          el: { text: 'Τα πρωινά του Δεκέμβρη είναι δροσερά, αυτό είναι όλο.', tr: 'Ta proiná tou Dekémvri eínai droserá, aftó eínai ólo.', say: 'ta pro-ee-NA too the-KEM-vree EE-neh thro-se-RA, af-TO EE-neh O-lo' },
          gloss: [['the mornings in December','ḍisembarnalli beḷigge','ta proiná tou Dekémvri'],['are cool','tampāgiruttade','eínai droserá'],['that is all','aṣṭē','aftó eínai ólo']],
          note: 'One Kannada word, aṣṭē, for the English "that is all" — aṣṭu (that much) plus the emphatic -ē.' },
        { en: 'My friend in Greece complains about the cold.',
          kn: { text: 'ಗ್ರೀಸ್\u200cನಲ್ಲಿರುವ ನನ್ನ ಸ್ನೇಹಿತ ಚಳಿಯ ಬಗ್ಗೆ ದೂರುತ್ತಾನೆ.', tr: 'grīsnalliruva nanna snēhita caḷiya bagge dūruttāne', say: 'GREES-nal-li-ru-va NAN-na SNEH-hi-ta CHA-ḷi-ya BAG-ge DOO-rut-TAA-ne' },
          el: { text: 'Ο φίλος μου στην Ελλάδα παραπονιέται για το κρύο.', tr: 'O fílos mou stin Elláda paraponiétai gia to krýo.', say: 'o FEE-los moo steen e-LA-tha pa-ra-po-NYE-teh ya to KREE-o' },
          gloss: [['my friend in Greece','grīsnalliruva nanna snēhita','o fílos mou stin Elláda'],['about the cold','caḷiya bagge','gia to krýo'],['complains','dūruttāne','paraponiétai']],
          note: 'Kannada turns "in Greece" into an adjective with -iruva: the in-Greece-being friend. It has no relative pronoun like "who".' },
        { en: 'I tell him to come here in January.',
          kn: { text: 'ಜನವರಿಯಲ್ಲಿ ಇಲ್ಲಿಗೆ ಬರುವಂತೆ ನಾನು ಅವನಿಗೆ ಹೇಳುತ್ತೇನೆ.', tr: 'janavariyalli illige baruvante nānu avanige hēḷuttēne', say: 'JA-na-va-ri-yal-li IL-li-ge ba-ru-VAN-te NAA-nu a-va-NI-ge heh-ḷut-TEH-ne' },
          el: { text: 'Του λέω να έρθει εδώ τον Ιανουάριο.', tr: 'Tou léo na érthei edó ton Ianouário.', say: 'too LEH-o na ER-thee e-THO ton ya-noo-A-ryo' },
          gloss: [['in January','janavariyalli','ton Ianouário'],['to come here','illige baruvante','na érthei edó'],['I tell him','avanige hēḷuttēne','tou léo']],
          note: 'Greek marks a month as a time expression with the bare accusative and its article: ton Ianouário.' },
        { en: 'He says the flights are too expensive.',
          kn: { text: 'ವಿಮಾನ ಟಿಕೆಟ್ ತುಂಬಾ ದುಬಾರಿ ಎಂದು ಅವನು ಹೇಳುತ್ತಾನೆ.', tr: 'vimāna ṭikeṭ tumbā dubāri endu avanu hēḷuttāne', say: 'vi-MAA-na ṬI-keṭ tum-BAA du-BAA-ri EN-du a-va-NU heh-ḷut-TAA-ne' },
          el: { text: 'Λέει ότι τα εισιτήρια είναι πολύ ακριβά.', tr: 'Léei óti ta eisitíria eínai polý akrivá.', say: 'LEH-ee O-tee ta ee-see-TEE-rya EE-neh po-LEE a-kree-VA' },
          gloss: [['the flights','vimāna ṭikeṭ','ta eisitíria'],['too expensive','tumbā dubāri','polý akrivá'],['he says','endu hēḷuttāne','léei óti']],
          note: 'Compare the two reported clauses: Kannada closes it with endu at the end, Greek opens it with óti at the start.' },
        { en: 'That is true, but so is the cold.',
          kn: { text: 'ಅದು ನಿಜ, ಆದರೆ ಚಳಿಯೂ ನಿಜ.', tr: 'adu nija, ādare caḷiyū nija', say: 'a-DU NI-ja, AA-da-re CHA-ḷi-yoo NI-ja' },
          el: { text: 'Αυτό είναι αλήθεια, αλλά και το κρύο.', tr: 'Aftó eínai alítheia, allá kai to krýo.', say: 'af-TO EE-neh a-LEE-thya, a-LA keh to KREE-o' },
          gloss: [['that is true','adu nija','aftó eínai alítheia'],['but so is the cold','ādare caḷiyū nija','allá kai to krýo']],
          note: 'Greek kai means both "and" and "also"; here it is the second. Kannada uses the -ū suffix again on caḷiyū.' },
        { en: 'We have been having this argument for six years.',
          kn: { text: 'ಆರು ವರ್ಷಗಳಿಂದ ನಾವು ಇದೇ ವಾದ ಮಾಡುತ್ತಿದ್ದೇವೆ.', tr: 'āru varṣagaḷinda nāvu idē vāda māḍuttiddēve', say: 'AA-ru VAR-sha-ga-ḷin-da NAA-vu i-DEH VAA-da maa-ḍut-tid-DEH-ve' },
          el: { text: 'Έξι χρόνια τώρα κάνουμε την ίδια κουβέντα.', tr: 'Éxi chrónia tóra kánoume tin ídia kouvénta.', say: 'EK-see KHRO-nya TO-ra KA-noo-meh teen EE-thya koo-VEN-da' },
          gloss: [['for six years','āru varṣagaḷinda','éxi chrónia tóra'],['the same argument','idē vāda','tin ídia kouvénta'],['we have been having','māḍuttiddēve','kánoume']],
          note: 'Greek adds tóra (now) to a plain present to mean "and still going". Kannada uses -inda, since.' },
        { en: 'Last year he finally came.',
          kn: { text: 'ಕಳೆದ ವರ್ಷ ಅವನು ಕೊನೆಗೂ ಬಂದ.', tr: 'kaḷeda varṣa avanu konegū banda', say: 'KA-ḷe-da VAR-sha a-va-NU KO-ne-goo BAN-da' },
          el: { text: 'Πέρσι ήρθε επιτέλους.', tr: 'Pérsi írthe epitélous.', say: 'PER-see EER-the e-pee-TEH-loos' },
          gloss: [['last year','kaḷeda varṣa','pérsi'],['finally','konegū','epitélous'],['he came','banda','írthe']],
          note: 'Greek has a single word for last year, pérsi. Kannada builds it from kaḷeda (passed) and varṣa (year).' },
        { en: 'He wore a jacket for the first two days.',
          kn: { text: 'ಮೊದಲ ಎರಡು ದಿನ ಅವನು ಜಾಕೆಟ್ ಹಾಕಿಕೊಂಡಿದ್ದ.', tr: 'modala eraḍu dina avanu jākeṭ hākikoṇḍidda', say: 'MO-da-la E-ra-ḍu DI-na a-va-NU JAA-keṭ haa-ki-koṇ-ḌID-da' },
          el: { text: 'Τις πρώτες δύο μέρες φορούσε μπουφάν.', tr: 'Tis prótes dýo méres foroúse boufán.', say: 'tees PRO-tes THEE-o MEH-res fo-ROO-se boo-FAN' },
          gloss: [['the first two days','modala eraḍu dina','tis prótes dýo méres'],['a jacket','jākeṭ','boufán'],['he wore','hākikoṇḍidda','foroúse']],
          note: 'Kannada hākikoḷḷu is "put on for oneself" — the -koḷḷu ending means the action comes back to the doer, like a reflexive.' },
        { en: 'After that he complained about the heat.',
          kn: { text: 'ಆಮೇಲೆ ಅವನು ಸೆಕೆಯ ಬಗ್ಗೆ ದೂರಿದ.', tr: 'āmēle avanu sekeya bagge dūrida', say: 'AA-meh-le a-va-NU SE-ke-ya BAG-ge DOO-ri-da' },
          el: { text: 'Μετά παραπονιόταν για τη ζέστη.', tr: 'Metá paraponiótan gia ti zésti.', say: 'me-TA pa-ra-po-NYO-tan ya tee ZEH-stee' },
          gloss: [['after that','āmēle','metá'],['about the heat','sekeya bagge','gia ti zésti'],['he complained','dūrida','paraponiótan']],
          note: 'The joke works in all three languages, which is the only real test of a translation.' },
        { en: 'He is coming again in November.',
          kn: { text: 'ಅವನು ನವೆಂಬರ್\u200cನಲ್ಲಿ ಮತ್ತೆ ಬರುತ್ತಿದ್ದಾನೆ.', tr: 'avanu navembarnalli matte baruttiddāne', say: 'a-va-NU na-VEM-bar-nal-li MAT-te ba-rut-tid-DAA-ne' },
          el: { text: 'Έρχεται πάλι τον Νοέμβριο.', tr: 'Érchetai páli ton Noémvrio.', say: 'ER-khe-teh PA-lee ton no-EM-vryo' },
          gloss: [['again','matte','páli'],['in November','navembarnalli','ton Noémvrio'],['he is coming','baruttiddāne','érchetai']],
          note: 'Both languages use the present tense for a settled future arrangement, exactly as English does with "he is coming".' },
    ]
},


];
