#!/usr/bin/env python3
"""seed_cookbooks.py — emit SQL for the starter cookbooks every user can read.

    python3 tools/seed_cookbooks.py > supabase/starter_cookbooks.sql

Six cookbooks, owned by nobody (user_id NULL, is_public true), so they appear
for anyone the first time they open CozyCookBook and cannot be edited or
deleted by anyone — the owner policies compare auth.uid() = user_id, which
never matches NULL.

Recipe ids are derived from the cookbook slug and recipe slug via uuid v5, so
re-running produces the same ids and the insert is idempotent. Ingredient names
are written the way the recipe reader wants them — quantity first, then the
food — because that is what the nutrition matcher in cozyhealth.js parses.
"""

import json, sys, uuid

NS = uuid.uuid5(uuid.NAMESPACE_URL, 'https://jeremyfrank101.github.io/cookbooks')

B, L, D, S = 'Breakfast', 'Lunch', 'Dinner', 'Snack'


def r(title, meal, ingredients, steps):
    return dict(title=title, meal=meal, ing=ingredients, steps=steps)


AMERICAN = [
 r('Buttermilk Pancakes', B,
   ['2 cups all-purpose flour','2 tbsp granulated sugar','2 tsp baking powder',
    '1 tsp baking soda','1 tsp salt','2 cups buttermilk','2 large eggs',
    '3 tbsp melted butter','Butter and maple syrup to serve'],
   ['Whisk the dry ingredients in a large bowl.',
    'Beat the buttermilk, eggs and melted butter together.',
    'Fold wet into dry until just combined — lumps are fine, overmixing makes them tough.',
    'Rest the batter 10 minutes while the griddle heats to medium.',
    'Cook 2-3 minutes until bubbles break on the surface, flip, 1-2 minutes more.',
    'Serve immediately with butter and warm syrup.']),
 r('Buttermilk Biscuits and Sausage Gravy', B,
   ['3 cups all-purpose flour','1 tbsp baking powder','1 tsp salt',
    '3/4 cup cold butter, cubed','1 cup buttermilk','1 lb breakfast sausage',
    '1/4 cup all-purpose flour','3 cups whole milk','1 tsp black pepper'],
   ['Heat the oven to 450°F.',
    'Cut the cold butter into the flour, baking powder and salt until it looks like coarse gravel.',
    'Stir in buttermilk just until it comes together. Pat to 1 inch, cut rounds, bake 12-15 minutes.',
    'Brown the sausage in a skillet, breaking it up as it cooks.',
    'Sprinkle the flour over the sausage and its fat; cook two minutes.',
    'Whisk in the milk and simmer until thick. Season hard with black pepper.',
    'Split the biscuits and drown them.']),
 r('Classic Eggs Benedict', B,
   ['4 English muffins, split','8 slices Canadian bacon','8 large eggs',
    '3 egg yolks','1 tbsp lemon juice','1 cup melted butter',
    '1 tbsp white vinegar','Pinch of cayenne','Salt to taste'],
   ['Blend the yolks and lemon juice, then stream in the hot melted butter until the hollandaise thickens. Season and keep warm.',
    'Toast the muffins and warm the Canadian bacon.',
    'Bring water and vinegar to a bare simmer; poach the eggs 3 minutes.',
    'Build: muffin, bacon, egg, hollandaise. Dust with cayenne.']),
 r('Blueberry Muffins', B,
   ['2 cups all-purpose flour','3/4 cup granulated sugar','2 tsp baking powder',
    '1/2 tsp salt','1/2 cup melted butter','1 cup milk','2 large eggs',
    '1 tsp vanilla extract','1 1/2 cups blueberries'],
   ['Heat the oven to 375°F and line a muffin tin.',
    'Whisk the dry ingredients together.',
    'Combine the butter, milk, eggs and vanilla; fold into the dry until barely mixed.',
    'Toss the blueberries in a spoonful of flour, then fold them in.',
    'Fill the cups high and bake 20-25 minutes until golden.']),
 r('Classic Cheeseburger', L,
   ['1 lb ground beef','4 burger buns','4 slices cheddar cheese',
    '1 yellow onion, sliced thin','1 tomato, sliced','4 leaves iceberg lettuce',
    'Dill pickles','Salt to taste','Black pepper to taste'],
   ['Divide the beef into four loose balls — do not compact them.',
    'Get a cast-iron pan screaming hot. Flatten each ball onto it and season.',
    'Sear 2 minutes for a hard crust, flip, add cheese, cook 2 minutes more.',
    'Toast the buns in the rendered fat.',
    'Build and rest one minute before eating.']),
 r('BLT Sandwich', L,
   ['8 slices bacon','4 slices bread, toasted','2 tomatoes, sliced',
    '4 leaves romaine lettuce','3 tbsp mayonnaise','Black pepper to taste'],
   ['Cook the bacon until crisp and drain it.',
    'Toast the bread and spread both sides with mayonnaise.',
    'Layer lettuce, tomato, bacon. Pepper the tomato generously.',
    'Cut on the diagonal.']),
 r('New England Clam Chowder', L,
   ['4 slices bacon, diced','1 yellow onion, diced','2 stalks celery, diced',
    '3 russet potatoes, cubed','2 cans chopped clams with juice','2 cups heavy cream',
    '3 tbsp all-purpose flour','2 fresh thyme sprigs','Salt to taste','Black pepper to taste'],
   ['Render the bacon; soften the onion and celery in the fat.',
    'Stir in the flour and cook two minutes.',
    'Add the clam juice and potatoes; simmer until the potatoes are tender.',
    'Add the cream and clams and heat through without boiling.',
    'Season and rest 10 minutes before serving — it improves.']),
 r('Cobb Salad', L,
   ['6 cups romaine lettuce, chopped','2 chicken breasts, grilled and sliced',
    '4 slices bacon, crisp','2 hard-boiled eggs, quartered','1 avocado, sliced',
    '1 cup cherry tomatoes, halved','1/2 cup blue cheese crumbles',
    '3 tbsp olive oil','1 tbsp red wine vinegar'],
   ['Arrange the lettuce on a wide platter.',
    'Lay the toppings in tidy stripes across it.',
    'Whisk the oil and vinegar with salt and pepper.',
    'Dress at the table so nothing wilts.']),
 r('Buffalo Chicken Wings', S,
   ['2 lbs chicken wings','1 tbsp baking powder','1 tsp salt',
    '1/2 cup hot sauce','1/4 cup butter','1 tbsp honey','Celery sticks to serve'],
   ['Dry the wings thoroughly and toss with baking powder and salt.',
    'Rest uncovered in the fridge an hour — dry skin is the whole trick.',
    'Bake at 425°F for 45 minutes, turning once.',
    'Melt the butter into the hot sauce and honey.',
    'Toss the wings in the sauce and serve with celery.']),
 r('Mac and Cheese', D,
   ['1 lb elbow macaroni','4 tbsp butter','1/4 cup all-purpose flour',
    '3 cups whole milk','3 cups shredded cheddar cheese','1 tsp mustard powder',
    '1/2 tsp black pepper','1 cup breadcrumbs'],
   ['Boil the macaroni one minute short of the package time.',
    'Make a roux with the butter and flour; whisk in the milk and simmer until thick.',
    'Off the heat, stir in the cheese, mustard and pepper.',
    'Fold in the pasta, top with breadcrumbs, bake at 375°F for 25 minutes.']),
 r('Meatloaf with Brown Gravy', D,
   ['2 lbs ground beef','1 cup breadcrumbs','1 yellow onion, grated',
    '2 large eggs','1/4 cup ketchup','2 tbsp Worcestershire sauce',
    '1 tsp salt','1 tsp black pepper','2 cups beef stock','2 tbsp all-purpose flour'],
   ['Mix everything but the stock and flour with your hands, gently.',
    'Shape into a free-form loaf on a sheet pan — a tin steams it.',
    'Bake at 350°F for an hour, glazing with more ketchup at the halfway mark.',
    'Rest 15 minutes. Make gravy from the pan drippings, flour and stock.']),
 r('Southern Fried Chicken', D,
   ['1 whole chicken, cut into 8 pieces','2 cups buttermilk','2 tbsp hot sauce',
    '3 cups all-purpose flour','1 tbsp sweet paprika','1 tsp cayenne',
    '2 tsp salt','1 tsp black pepper','Oil for frying'],
   ['Brine the chicken in buttermilk and hot sauce overnight.',
    'Season the flour heavily — it is the only seasoning the crust gets.',
    'Dredge each piece, pressing hard, and rest 15 minutes so the coating sets.',
    'Fry at 325°F, dark meat 14 minutes, white meat 12, until 165°F inside.',
    'Drain on a rack, never on paper.']),
 r('Pot Roast with Root Vegetables', D,
   ['3 lb chuck roast','2 tbsp olive oil','1 yellow onion, quartered',
    '4 carrots, chunked','3 parsnips, chunked','4 russet potatoes, halved',
    '3 cloves garlic, minced','2 cups beef stock','2 fresh rosemary sprigs',
    'Salt to taste','Black pepper to taste'],
   ['Season and sear the roast hard on every side in a heavy pot.',
    'Remove it, soften the onion and garlic, then deglaze with the stock.',
    'Return the meat, cover, and braise at 300°F for three hours.',
    'Add the root vegetables for the final hour.',
    'The roast is ready when a fork twists out with no resistance.']),
 r('Grilled Ribeye with Garlic Butter', D,
   ['2 ribeye steaks','2 tbsp olive oil','4 cloves garlic, minced',
    '4 tbsp butter','2 fresh thyme sprigs','Salt to taste','Black pepper to taste'],
   ['Take the steaks out an hour early and salt them.',
    'Sear over the hottest part of the grill, 3 minutes a side.',
    'Move to indirect heat and cook to 130°F for medium-rare.',
    'Rest 10 minutes under garlic-thyme butter.']),
 r('Baby Back Ribs', D,
   ['2 racks baby back ribs','1/4 cup brown sugar','2 tbsp sweet paprika',
    '1 tbsp salt','1 tbsp black pepper','1 tsp cayenne','1 cup barbecue sauce'],
   ['Pull the membrane off the bone side — it never softens.',
    'Rub with the sugar and spices and rest an hour.',
    'Bake wrapped in foil at 275°F for 2.5 hours.',
    'Unwrap, sauce, and finish under the broiler until it bubbles and chars at the edges.']),
 r('Thanksgiving Roast Turkey', D,
   ['1 whole turkey, 12-14 lbs','1 cup butter, softened','2 yellow onions, quartered',
    '4 stalks celery, chunked','2 lemons, halved','4 fresh sage sprigs',
    '4 fresh thyme sprigs','2 tbsp salt','1 tbsp black pepper'],
   ['Dry-brine the bird with salt for 24 hours, uncovered, in the fridge.',
    'Work the softened butter under the breast skin.',
    'Stuff the cavity with the aromatics — for flavour, not for eating.',
    'Roast at 425°F for 30 minutes, drop to 325°F for about 2.5 hours.',
    'Pull at 160°F in the breast; it climbs while resting. Rest 30 minutes.']),
 r('Cornbread', S,
   ['1 cup cornmeal','1 cup all-purpose flour','1/4 cup granulated sugar',
    '1 tbsp baking powder','1 tsp salt','1 cup buttermilk','2 large eggs',
    '1/3 cup melted butter'],
   ['Heat a cast-iron skillet with a spoon of butter in a 425°F oven.',
    'Whisk the dry, whisk the wet, combine quickly.',
    'Pour into the hot skillet — the sizzle makes the crust.',
    'Bake 20-25 minutes until the top springs back.']),
 r('Coleslaw', S,
   ['1 bag coleslaw mix','1/2 cup mayonnaise','2 tbsp apple cider vinegar',
    '1 tbsp granulated sugar','1 tsp celery seed','Salt to taste','Black pepper to taste'],
   ['Whisk the dressing until the sugar dissolves.',
    'Toss with the cabbage mix.',
    'Chill at least an hour so it slumps and the flavours settle.']),
 r('Apple Pie', S,
   ['2 pie crusts','6 Granny Smith apples, sliced','3/4 cup granulated sugar',
    '2 tbsp all-purpose flour','1 tsp cinnamon','1/4 tsp nutmeg',
    '1 tbsp lemon juice','2 tbsp butter','1 egg, beaten'],
   ['Toss the apples with sugar, flour, spices and lemon; rest 30 minutes and drain the syrup.',
    'Reduce that syrup in a pan until thick and pour it back over the apples — this is what stops a soupy pie.',
    'Fill the crust, dot with butter, lid it, cut vents, brush with egg.',
    'Bake at 425°F for 20 minutes, then 375°F for 40 more.',
    'Cool completely. Cutting it warm will ruin it.']),
 r('New York Cheesecake', S,
   ['2 cups graham cracker crumbs','1/2 cup melted butter','32 oz cream cheese',
    '1 1/2 cups granulated sugar','4 large eggs','1 cup sour cream',
    '2 tsp vanilla extract','1/4 cup all-purpose flour'],
   ['Press the crumbs and butter into a springform tin and bake 10 minutes at 350°F.',
    'Beat the cream cheese and sugar smooth, then the eggs one at a time on low — air is the enemy.',
    'Fold in the sour cream, vanilla and flour.',
    'Bake in a water bath at 325°F for 90 minutes until the centre still wobbles.',
    'Cool in the switched-off oven with the door ajar, then chill overnight.']),
 r('Chocolate Chip Cookies', S,
   ['2 1/4 cups all-purpose flour','1 tsp baking soda','1 tsp salt',
    '1 cup butter, softened','3/4 cup granulated sugar','3/4 cup brown sugar',
    '2 large eggs','2 tsp vanilla extract','2 cups chocolate chips'],
   ['Cream the butter and both sugars until pale and fluffy.',
    'Beat in the eggs and vanilla, then the dry ingredients.',
    'Fold in the chips and chill the dough at least two hours.',
    'Bake at 375°F for 9-11 minutes. Pull them looking underdone.']),
 r('Brownies', S,
   ['1 cup butter','2 cups granulated sugar','4 large eggs',
    '1 cup cocoa powder','1 cup all-purpose flour','1 tsp salt',
    '2 tsp vanilla extract','1 cup chocolate chips'],
   ['Melt the butter and whisk in the sugar and cocoa while warm.',
    'Beat in the eggs one at a time, hard, for a shiny crust.',
    'Fold in the flour, salt and vanilla, then the chips.',
    'Bake at 350°F for 30 minutes. A few crumbs on the skewer means stop.']),
 r('Banana Bread', S,
   ['3 ripe bananas, mashed','1/3 cup melted butter','3/4 cup granulated sugar',
    '1 large egg','1 tsp vanilla extract','1 tsp baking soda','Pinch of salt',
    '1 1/2 cups all-purpose flour'],
   ['Mash the bananas — the blacker the better.',
    'Stir in the butter, sugar, egg and vanilla.',
    'Fold in the soda, salt and flour until just combined.',
    'Bake at 350°F for 55-60 minutes.']),
]

ITALIAN = [
 r('Cornetto and Cappuccino', B,
   ['4 cornetti','2 cups whole milk','4 shots espresso','Granulated sugar to taste'],
   ['Warm the cornetti briefly so the sugar on top just catches.',
    'Pull four espressos.',
    'Steam the milk to a fine wet paint texture, not stiff foam.',
    'Pour a third milk, two thirds coffee. Standing at the counter is traditional.']),
 r('Torta della Nonna', B,
   ['2 cups all-purpose flour','1/2 cup granulated sugar','1/2 cup butter, cold',
    '3 large eggs','2 cups whole milk','1 lemon, zested','1/4 cup cornstarch',
    '1/2 cup pine nuts','1 tsp vanilla extract'],
   ['Make a short pastry with the flour, sugar, cold butter and one egg. Chill it.',
    'Heat the milk with the lemon zest.',
    'Whisk the remaining eggs, sugar and cornstarch, temper in the milk, and cook to a thick custard.',
    'Line a tin with two-thirds of the pastry, fill, lid it, and scatter pine nuts.',
    'Bake at 350°F for 40 minutes and dust with icing sugar.']),
 r('Uova in Purgatorio', B,
   ['4 large eggs','1 can crushed tomatoes','3 cloves garlic, sliced',
    '3 tbsp olive oil','1/4 tsp chili flakes','1/4 cup fresh basil',
    'Salt to taste','Crusty bread to serve'],
   ['Soften the garlic and chili in olive oil without colouring it.',
    'Add the tomatoes and simmer 15 minutes until the sauce is no longer watery.',
    'Make wells and crack in the eggs. Cover and cook until the whites set.',
    'Basil over the top, bread alongside.']),
 r('Spaghetti Carbonara', L,
   ['1 lb spaghetti','8 oz guanciale, diced','4 large eggs','2 egg yolks',
    '1 1/2 cups Pecorino Romano, grated','2 tsp black pepper','Salt to taste'],
   ['Render the guanciale slowly until the fat runs and the meat crisps.',
    'Beat the eggs, yolks, cheese and a great deal of black pepper.',
    'Cook the spaghetti and save a mug of the water.',
    'Off the heat — genuinely off — toss the pasta with the fat, then the egg mixture, loosening with pasta water.',
    'No cream. The sauce is egg and starch and nothing else.']),
 r('Cacio e Pepe', L,
   ['1 lb tonnarelli or spaghetti','2 cups Pecorino Romano, grated',
    '1 tbsp black pepper, coarsely cracked','Salt to taste'],
   ['Toast the pepper in a dry pan until it smells of pepper rather than dust.',
    'Cook the pasta in deliberately under-salted, minimal water so it goes starchy.',
    'Make a paste of pecorino and a little cool pasta water — cool, or it clumps.',
    'Toss everything off the heat, adding water until it turns glossy.']),
 r('Panzanella', L,
   ['4 cups stale bread, torn','4 heirloom tomatoes, chunked','1 cucumber, sliced',
    '1 red onion, sliced thin','1/2 cup fresh basil','1/3 cup olive oil',
    '3 tbsp red wine vinegar','Salt to taste'],
   ['Salt the tomatoes in a colander for 20 minutes and keep the juice.',
    'Soak the bread in that juice with the vinegar.',
    'Toss everything with the oil and let it sit half an hour.',
    'It should be soft but not mush — stale bread matters.']),
 r('Minestrone', L,
   ['2 tbsp olive oil','1 cup mirepoix','2 cloves garlic, minced',
    '1 can cannellini beans','1 can diced tomatoes','1 zucchini, diced',
    '2 cups green beans','6 cups vegetable stock','1 cup small pasta',
    '1/4 cup fresh basil','Parmesan rind'],
   ['Soften the mirepoix in oil for a full ten minutes.',
    'Add the garlic, tomatoes and stock with the parmesan rind.',
    'Simmer 30 minutes, then add the beans and vegetables.',
    'Cook the pasta in the soup at the end so it releases its starch.']),
 r('Margherita Pizza', L,
   ['500g bread flour','325ml water','10g salt','3g active dry yeast',
    '1 can San Marzano tomatoes','250g fresh mozzarella','1/4 cup fresh basil',
    '3 tbsp olive oil'],
   ['Mix the dough and rest 20 minutes, then knead briefly and prove 24 hours in the fridge.',
    'Ball the dough and let it come to room temperature for 4 hours.',
    'Crush the tomatoes by hand with salt — do not cook them.',
    'Stretch by hand, never with a rolling pin.',
    'Bake as hot as your oven goes, on a preheated stone, 6-8 minutes.',
    'Basil goes on after the oven, not before.']),
 r('Risotto alla Milanese', D,
   ['1 1/2 cups arborio rice','1 pinch saffron threads','1 yellow onion, minced',
    '1/2 cup white wine','6 cups chicken stock','4 tbsp butter',
    '1 cup Parmesan, grated','Salt to taste'],
   ['Steep the saffron in a ladle of warm stock.',
    'Soften the onion in butter; toast the rice until the edges turn translucent.',
    'Deglaze with wine and let it disappear.',
    'Add hot stock a ladle at a time, stirring, for about 18 minutes.',
    'Off the heat, beat in cold butter and parmesan hard. It should ripple on the plate.']),
 r('Lasagne alla Bolognese', D,
   ['1 lb lasagne sheets','1 lb ground beef','8 oz pancetta, diced',
    '1 cup mirepoix','1 cup whole milk','1 cup red wine','1 can crushed tomatoes',
    '4 tbsp butter','1/4 cup all-purpose flour','4 cups whole milk',
    '2 cups Parmesan, grated','Pinch of nutmeg'],
   ['Brown the pancetta and beef, then soften the mirepoix in the fat.',
    'Add the milk and cook it away — this is what makes the meat tender.',
    'Add the wine, cook it away, then the tomatoes. Simmer three hours.',
    'Make a béchamel with the butter, flour, milk and nutmeg.',
    'Layer ragù, béchamel, pasta, parmesan, ending with béchamel.',
    'Bake at 375°F for 45 minutes and rest 20 before cutting.']),
 r('Osso Buco', D,
   ['4 veal shanks','1/2 cup all-purpose flour','1 cup mirepoix',
    '1 cup white wine','2 cups chicken stock','1 can diced tomatoes',
    '2 fresh rosemary sprigs','1 lemon, zested','2 cloves garlic, minced',
    '1/4 cup fresh parsley'],
   ['Tie each shank so it holds together, dredge in flour, and brown deeply.',
    'Soften the mirepoix, deglaze with wine, add stock, tomatoes and herbs.',
    'Braise covered at 325°F for two hours until the meat gives.',
    'Mix the lemon zest, garlic and parsley into a gremolata and scatter it over at the table.']),
 r('Chicken Piccata', D,
   ['4 chicken breasts, pounded thin','1/2 cup all-purpose flour','3 tbsp olive oil',
    '4 tbsp butter','1/2 cup white wine','1/2 cup chicken stock',
    '3 tbsp lemon juice','3 tbsp capers','1/4 cup fresh parsley'],
   ['Pound the chicken to an even thickness and dredge in seasoned flour.',
    'Sear in oil and butter, 3 minutes a side, then set aside.',
    'Deglaze with wine, add stock, lemon and capers, and reduce by half.',
    'Swirl in cold butter off the heat and return the chicken to coat.']),
 r('Melanzane alla Parmigiana', D,
   ['3 eggplants, sliced','2 cups all-purpose flour','4 large eggs, beaten',
    'Oil for frying','1 can crushed tomatoes','3 cloves garlic, sliced',
    '500g fresh mozzarella','1 1/2 cups Parmesan, grated','1/4 cup fresh basil'],
   ['Salt the eggplant slices and drain them an hour. This is not optional.',
    'Flour, egg, and shallow-fry until golden. Drain well.',
    'Simmer the tomatoes with garlic and basil for 20 minutes.',
    'Layer eggplant, sauce, both cheeses, and repeat.',
    'Bake at 375°F for 40 minutes and rest 15 minutes.']),
 r('Cacciatore', D,
   ['8 chicken thighs','2 tbsp olive oil','1 red bell pepper, sliced',
    '1 yellow onion, sliced','8 oz cremini mushrooms, sliced','3 cloves garlic, minced',
    '1/2 cup red wine','1 can diced tomatoes','2 fresh rosemary sprigs',
    'Salt to taste','Black pepper to taste'],
   ['Brown the thighs skin-side down until the skin releases on its own.',
    'Soften the pepper, onion and mushrooms in the rendered fat.',
    'Deglaze with wine, add tomatoes and rosemary, return the chicken.',
    'Simmer uncovered 40 minutes so the sauce tightens around it.']),
 r('Linguine alle Vongole', D,
   ['1 lb linguine','2 lbs clams, scrubbed','4 cloves garlic, sliced',
    '1/3 cup olive oil','1/2 cup white wine','1/4 tsp chili flakes',
    '1/4 cup fresh parsley','Salt to taste'],
   ['Purge the clams in salted water for an hour.',
    'Soften the garlic and chili in oil; add the clams and wine and cover.',
    'Pull each clam out the moment it opens so none overcook.',
    'Cook the linguine very al dente and finish it in the clam liquor.',
    'Return the clams, add parsley, and toss hard to emulsify.']),
 r('Tiramisu', S,
   ['6 egg yolks','3/4 cup granulated sugar','500g mascarpone',
    '1 1/2 cups heavy cream','2 cups strong espresso, cooled',
    '1/4 cup Marsala wine','2 packages ladyfingers','Cocoa powder for dusting'],
   ['Whisk the yolks and sugar over a bain-marie until thick and pale, then cool.',
    'Fold in the mascarpone, then softly whipped cream.',
    'Combine the espresso and Marsala. Dip each ladyfinger for one second only.',
    'Layer biscuits and cream twice. Chill six hours.',
    'Dust with cocoa immediately before serving, never before.']),
 r('Panna Cotta', S,
   ['2 cups heavy cream','1/2 cup whole milk','1/2 cup granulated sugar',
    '1 tsp vanilla extract','2 tsp gelatin','2 tbsp cold water','1 cup berries'],
   ['Bloom the gelatin in the cold water.',
    'Heat the cream, milk, sugar and vanilla to a bare steam — do not boil.',
    'Stir in the gelatin until dissolved.',
    'Pour into moulds and chill four hours. It should barely hold its shape.',
    'Serve with macerated berries.']),
 r('Cannoli', S,
   ['12 cannoli shells','500g ricotta, drained overnight','3/4 cup powdered sugar',
    '1/2 tsp cinnamon','1/2 cup chocolate chips','1/4 cup pistachios, chopped',
    '1 orange, zested'],
   ['Drain the ricotta overnight in cheesecloth — wet filling ruins the shells.',
    'Beat it smooth with the sugar, cinnamon and orange zest.',
    'Fold in the chocolate chips.',
    'Fill only at the moment of serving, and dip the ends in pistachios.']),
 r('Affogato', S,
   ['4 scoops vanilla gelato','4 shots hot espresso','2 tbsp chopped hazelnuts'],
   ['Put the gelato in cold glasses.',
    'Pull the espresso and pour it over at the table.',
    'Hazelnuts on top. Eat before it collapses.']),
 r('Biscotti di Prato', S,
   ['2 cups all-purpose flour','1 cup granulated sugar','2 large eggs',
    '1 tsp baking powder','1 cup almonds, whole','1 tsp vanilla extract',
    '1 orange, zested','Pinch of salt'],
   ['Mix everything into a stiff dough with the almonds whole.',
    'Shape into two logs and bake at 350°F for 25 minutes.',
    'Cool 10 minutes, slice on the diagonal, then bake again 12 minutes a side.',
    'They should be hard. They are meant to be dunked in Vin Santo.']),
 r('Focaccia', S,
   ['500g bread flour','400ml water','10g salt','5g active dry yeast',
    '1/3 cup olive oil','2 fresh rosemary sprigs','Flaky salt to finish'],
   ['Mix a very wet dough and fold it four times over two hours.',
    'Prove overnight in the fridge.',
    'Pour a generous layer of oil into the tin and stretch the dough into it.',
    'Dimple hard with your fingers, right to the bottom. Rosemary and flaky salt.',
    'Bake at 450°F for 25 minutes until the base is crisp in the oil.']),
]

NORTH_INDIAN = [
 r('Aloo Paratha', B,
   ['2 cups whole wheat flour','3 russet potatoes, boiled and mashed',
    '1 yellow onion, minced','2 green chilies, minced','1 tsp ground cumin',
    '1 tsp garam masala','1/4 cup fresh cilantro','4 tbsp ghee','Salt to taste'],
   ['Knead a soft dough with the flour, water and a little salt; rest 30 minutes.',
    'Mix the mashed potato with onion, chilies, spices and cilantro.',
    'Stuff each ball of dough with filling and seal it carefully.',
    'Roll gently and cook on a hot tawa with ghee until both sides blister.',
    'Serve with yogurt and pickle.']),
 r('Chole Bhature', B,
   ['2 cups chickpeas, soaked overnight','2 yellow onions, pureed',
    '3 tomatoes, pureed','2 tbsp ginger garlic paste','2 tsp chole masala',
    '1 tsp ground turmeric','2 cups all-purpose flour','1/2 cup yogurt',
    '1/4 cup ghee','Oil for frying'],
   ['Pressure-cook the chickpeas with a tea bag for colour, then discard the bag.',
    'Fry the onion puree until it darkens properly, then the ginger garlic paste.',
    'Add the tomato puree and spices and cook until the oil separates.',
    'Add the chickpeas with their liquor and simmer 20 minutes.',
    'For bhature, make a yogurt dough, rest two hours, and deep-fry until they balloon.']),
 r('Masala Chai', B,
   ['2 cups water','2 cups whole milk','3 tbsp black tea leaves',
    '4 green cardamom pods','1 inch fresh ginger, grated','2 cloves',
    '1 cinnamon stick','3 tbsp granulated sugar'],
   ['Crush the cardamom, cloves and cinnamon roughly.',
    'Boil them in water with the ginger for five minutes.',
    'Add the tea and boil two minutes more.',
    'Add the milk and sugar and bring to a boil three times, pulling it off each time.',
    'Strain from a height.']),
 r('Poha', B,
   ['2 cups poha','1 yellow onion, diced','2 green chilies, slit',
    '1 tsp mustard seeds','10 fresh curry leaves','1/2 tsp ground turmeric',
    '2 tbsp peanuts','2 tbsp oil','1 lemon','1/4 cup fresh cilantro'],
   ['Rinse the poha in a sieve until just soft; never soak it.',
    'Temper mustard seeds, curry leaves and peanuts in hot oil.',
    'Add the onion and chilies and soften; then the turmeric.',
    'Fold in the poha gently and steam covered two minutes.',
    'Lemon and cilantro at the end.']),
 r('Rajma Chawal', L,
   ['2 cups kidney beans, soaked overnight','2 yellow onions, minced',
    '3 tomatoes, pureed','2 tbsp ginger garlic paste','1 tsp ground cumin',
    '1 tsp ground coriander','1 tsp garam masala','1/2 tsp ground turmeric',
    '3 tbsp ghee','2 cups basmati rice'],
   ['Pressure-cook the beans until they crush easily between two fingers.',
    'Brown the onions in ghee slowly — 15 minutes, not five.',
    'Add ginger garlic paste, then tomato puree and spices; cook until the oil separates.',
    'Add the beans with their cooking water and simmer 30 minutes.',
    'Mash a ladleful against the side to thicken it. Serve over rice.']),
 r('Chana Masala', L,
   ['2 cups chickpeas, cooked','1 yellow onion, minced','2 tomatoes, pureed',
    '1 tbsp ginger garlic paste','2 tsp chana masala','1 tsp ground cumin',
    '1/2 tsp ground turmeric','1 tsp amchur','3 tbsp oil','1/4 cup fresh cilantro'],
   ['Brown the onion well, then add the ginger garlic paste.',
    'Add the tomato and ground spices, cooking until the mixture leaves the pan.',
    'Add the chickpeas and a cup of water; simmer 20 minutes.',
    'Finish with amchur for sourness and plenty of cilantro.']),
 r('Chicken Tikka Masala', D,
   ['2 lbs chicken thighs, cubed','1 cup yogurt','2 tbsp ginger garlic paste',
    '2 tsp garam masala','1 tsp ground turmeric','2 tsp sweet paprika',
    '1 yellow onion, minced','1 can crushed tomatoes','1 cup heavy cream',
    '4 tbsp butter','1 tbsp kasuri methi'],
   ['Marinate the chicken in yogurt, ginger garlic paste and half the spices for four hours.',
    'Grill or broil the chicken until charred at the edges. Char is the point.',
    'Soften the onion in butter, add the remaining spices and the tomatoes.',
    'Simmer 20 minutes, then blend smooth and return to the pan.',
    'Add cream and the grilled chicken; simmer 10 minutes.',
    'Crush the kasuri methi between your palms over the pan at the end.']),
 r('Butter Chicken', D,
   ['2 lbs chicken thighs','1 cup yogurt','2 tbsp ginger garlic paste',
    '2 tsp garam masala','1 can crushed tomatoes','1 cup heavy cream',
    '6 tbsp butter','1 tbsp honey','1 tsp kashmiri chili powder',
    '1 tbsp kasuri methi'],
   ['Marinate and grill the chicken as for tikka.',
    'Simmer the tomatoes with chili powder and butter for 25 minutes, then blend.',
    'Pass the sauce through a sieve — this is what makes it velvety.',
    'Add cream, honey and the chicken and warm through gently.',
    'Finish with kasuri methi and a knob of cold butter.']),
 r('Rogan Josh', D,
   ['2 lbs lamb shoulder, cubed','1 cup yogurt','2 tsp kashmiri chili powder',
    '1 tsp ground fennel','1 tsp ground ginger','4 green cardamom pods',
    '2 black cardamom pods','1 cinnamon stick','4 tbsp ghee','1 pinch asafoetida'],
   ['Brown the lamb in ghee in batches and set aside.',
    'Bloom the whole spices and asafoetida in the fat.',
    'Whisk the yogurt and add it off the heat, a spoon at a time, so it does not split.',
    'Return the lamb, cover, and cook 90 minutes until the sauce clings and reddens.']),
 r('Palak Paneer', D,
   ['1 lb paneer, cubed','2 lbs spinach','1 yellow onion, minced',
    '2 green chilies','1 tbsp ginger garlic paste','1 tsp ground cumin',
    '1/2 tsp garam masala','3 tbsp ghee','1/4 cup heavy cream'],
   ['Blanch the spinach 90 seconds and shock it in ice water — this keeps it green.',
    'Blend with the green chilies to a coarse puree.',
    'Brown the onion in ghee, add ginger garlic paste and the ground spices.',
    'Add the spinach puree and cook only five minutes; longer turns it grey.',
    'Fold in the paneer and cream.']),
 r('Dal Makhani', D,
   ['1 cup whole black urad dal','1/4 cup kidney beans','1 tbsp ginger garlic paste',
    '2 tomatoes, pureed','4 tbsp butter','1/2 cup heavy cream',
    '1 tsp garam masala','1 tsp kashmiri chili powder','1 tbsp kasuri methi'],
   ['Soak the dal and beans overnight, then pressure-cook until completely soft.',
    'Fry the ginger garlic paste and tomato puree with the spices until the oil separates.',
    'Combine and simmer on the lowest possible heat for two hours, stirring often.',
    'Add butter and cream in the last 20 minutes.',
    'The long slow cooking is the entire recipe. There is no shortcut.']),
 r('Malai Kofta', D,
   ['1 cup paneer, grated','2 russet potatoes, boiled and mashed',
    '3 tbsp cornstarch','2 tbsp raisins','2 tbsp cashews','Oil for frying',
    '1 yellow onion, pureed','1/2 cup cashew paste','1 cup heavy cream',
    '1 tsp garam masala','3 tbsp ghee'],
   ['Mix paneer, potato and cornstarch; stuff each ball with a raisin and a cashew.',
    'Fry the kofta until golden and drain them.',
    'Cook the onion puree in ghee without browning it — this gravy stays pale.',
    'Add cashew paste, cream and garam masala and simmer gently.',
    'Add the kofta only at the table, or they dissolve.']),
 r('Biryani', D,
   ['3 cups basmati rice','2 lbs chicken, bone-in','1 cup yogurt',
    '3 yellow onions, sliced thin','1 pinch saffron threads','1/4 cup whole milk',
    '2 tsp biryani masala','1/4 cup fresh mint','1/4 cup fresh cilantro',
    '4 tbsp ghee','4 green cardamom pods'],
   ['Fry the onions slowly until deep brown and crisp; reserve half.',
    'Marinate the chicken in yogurt, half the fried onions and the masala for two hours.',
    'Parboil the rice with whole spices to 70 percent — it finishes in the steam.',
    'Layer chicken, rice, herbs, saffron milk and the rest of the onions.',
    'Seal the pot with dough or foil and cook on the lowest heat 25 minutes.',
    'Do not stir it. Bring it to the table sealed and open it there.']),
 r('Baingan Bharta', D,
   ['2 large eggplants','1 yellow onion, minced','3 tomatoes, diced',
    '1 tbsp ginger garlic paste','2 green chilies, minced','1 tsp ground cumin',
    '1/2 tsp ground turmeric','3 tbsp oil','1/4 cup fresh cilantro'],
   ['Char the eggplants directly over a flame until the skin blackens and collapses.',
    'Cool, peel, and mash the smoky flesh.',
    'Brown the onion, add ginger garlic paste, chilies and tomatoes.',
    'Cook until jammy, then fold in the eggplant and cook 10 minutes more.']),
 r('Naan', S,
   ['3 cups all-purpose flour','1/2 cup yogurt','1 tsp active dry yeast',
    '1 tsp granulated sugar','1/2 cup warm milk','3 tbsp ghee','1 tsp salt',
    '1 tbsp nigella seeds'],
   ['Proof the yeast in the warm milk with the sugar.',
    'Knead a soft dough with the flour, yogurt and salt; prove two hours.',
    'Roll into teardrops and slap onto the hottest dry pan you own.',
    'When it bubbles, flip and press. Brush with ghee and scatter nigella seeds.']),
 r('Jeera Rice', S,
   ['2 cups basmati rice','2 tsp cumin seeds','3 tbsp ghee',
    '1 bay leaf','4 green cardamom pods','Salt to taste'],
   ['Rinse the rice until the water runs clear, then soak 30 minutes.',
    'Bloom the cumin and whole spices in ghee until they crackle.',
    'Add the drained rice and toast two minutes.',
    'Add water at 1:1.5, boil, then cover and cook on the lowest heat 12 minutes.',
    'Rest 10 minutes before fluffing.']),
 r('Raita', S,
   ['2 cups yogurt','1 cucumber, grated','1/2 tsp ground cumin',
    '1/4 cup fresh mint','1/4 tsp black salt','Salt to taste'],
   ['Squeeze the water out of the grated cucumber.',
    'Whisk the yogurt smooth and fold everything together.',
    'Toast and grind the cumin yourself if you can — it is most of the flavour.']),
 r('Samosa', S,
   ['2 cups all-purpose flour','1/4 cup ghee','4 russet potatoes, boiled',
    '1 cup English peas','1 tsp ground cumin','1 tsp garam masala',
    '1 tsp amchur','2 green chilies, minced','Oil for frying'],
   ['Rub the ghee into the flour until it holds shape when squeezed, then add water sparingly.',
    'Rest the dough 30 minutes — a short dough gives the blistered shell.',
    'Mash the potatoes coarsely with peas, spices and chilies.',
    'Cut circles in half, form cones, fill and seal with water.',
    'Fry at a low 300°F until pale, then again hot until deep gold.']),
 r('Gulab Jamun', S,
   ['1 cup milk powder','1/4 cup all-purpose flour','1/4 tsp baking powder',
    '3 tbsp ghee','1/4 cup whole milk','2 cups granulated sugar','2 cups water',
    '4 green cardamom pods','1 tbsp rose water'],
   ['Make a soft dough and rest it 10 minutes. Handle it as little as possible.',
    'Roll crack-free balls — any seam splits in the oil.',
    'Fry very gently at low heat, moving constantly, until deep brown.',
    'Boil the sugar and water with cardamom into a thin syrup.',
    'Drop the hot jamun into warm syrup and soak two hours.']),
 r('Kheer', S,
   ['1/2 cup basmati rice','6 cups whole milk','1/2 cup granulated sugar',
    '4 green cardamom pods','2 tbsp almonds, slivered','2 tbsp pistachios',
    '1 pinch saffron threads'],
   ['Soak the rice 20 minutes, then drain.',
    'Simmer it in the milk on low, stirring often, for 45 minutes until it thickens.',
    'Add sugar only at the end — earlier and the rice stays hard.',
    'Stir in cardamom, saffron and nuts. Good warm or cold.']),
 r('Mango Lassi', S,
   ['2 cups yogurt','2 cups mango, diced','1/2 cup whole milk',
    '3 tbsp granulated sugar','4 green cardamom pods, ground','Ice'],
   ['Blend everything until completely smooth.',
    'Adjust with milk to a drinkable thickness.',
    'Serve very cold with a pinch of ground cardamom on top.']),
]

SOUTH_INDIAN = [
 r('Plain Dosa', B,
   ['3 cups idli rice','1 cup urad dal','1 tsp fenugreek seeds',
    '1/2 cup poha','Rock salt to taste','3 tbsp ghee'],
   ['Soak the rice and the dal separately, with the fenugreek in the dal, for six hours.',
    'Grind the dal first to a light foam, then the rice to a fine grit.',
    'Combine by hand — the warmth of your hands starts the ferment.',
    'Ferment 8-12 hours until risen and sour-smelling.',
    'Thin with water and spread on a hot tawa in one confident spiral.',
    'Ghee round the edges; cook only one side.']),
 r("Idli - Ajji's Way", B,
   ['3 cups idli rice','1 cup urad dal','1/2 cup poha','1 tsp fenugreek seeds',
    'Rock salt to taste','1 tbsp ghee'],
   ['Soak rice, dal, poha and fenugreek as for dosa but grind the batter thicker.',
    'Ferment overnight somewhere warm until doubled.',
    'Add rock salt only after fermenting — regular salt slows the culture.',
    'Grease the plates with ghee and steam 12 minutes.',
    'A skewer should come out clean and the idli should slide off the plate on its own.']),
 r('Masala Dosa', B,
   ['1 batch dosa batter','4 russet potatoes, boiled','1 yellow onion, sliced',
    '1 tsp mustard seeds','10 fresh curry leaves','2 green chilies, slit',
    '1/2 tsp ground turmeric','3 tbsp oil','1/4 cup fresh cilantro'],
   ['Temper mustard seeds and curry leaves in oil until they pop.',
    'Add onion, chilies and turmeric; soften without browning.',
    'Fold in the crushed potato and cilantro. Keep it coarse.',
    'Spread the dosa, place the filling on one half, and fold over.']),
 r('Upma', B,
   ['1 cup semolina','1 yellow onion, diced','1 tsp mustard seeds',
    '1 tbsp urad dal','10 fresh curry leaves','2 green chilies, slit',
    '1 inch fresh ginger, minced','3 tbsp ghee','1 lemon'],
   ['Dry-roast the semolina until it smells nutty, then set aside.',
    'Temper mustard seeds, urad dal and curry leaves in ghee.',
    'Add onion, ginger and chilies and soften.',
    'Add three cups of boiling water, then rain in the semolina while stirring hard.',
    'Cover two minutes off the heat. Lemon at the end.']),
 r('Medu Vada', B,
   ['1 cup urad dal','2 green chilies, minced','1 inch fresh ginger, minced',
    '10 fresh curry leaves','1 tsp black pepper, cracked','Salt to taste',
    'Oil for frying'],
   ['Soak the dal four hours and grind with almost no water into a stiff fluffy batter.',
    'Beat the batter by hand for five minutes — it should float in water.',
    'Fold in chilies, ginger, curry leaves and pepper.',
    'Wet your palm, flatten a ball, make a hole, and slide it into hot oil.',
    'Fry until deep gold. Serve with sambar and chutney.']),
 r('Sambar', L,
   ['1 cup toor dal','1 tbsp tamarind paste','1 yellow onion, chunked',
    '1 carrot, chunked','1 cup okra','2 tomatoes, chunked',
    '3 tbsp sambar powder','1 tsp mustard seeds','10 fresh curry leaves',
    '1/4 tsp asafoetida','3 tbsp oil'],
   ['Cook the toor dal until it collapses, then whisk it smooth.',
    'Simmer the vegetables with tamarind and sambar powder until tender.',
    'Combine with the dal and loosen with water to a pourable consistency.',
    'Temper mustard seeds, curry leaves and asafoetida in hot oil and pour it in.',
    'The tempering goes in at the very end, off the heat.']),
 r('Rasam', L,
   ['1/2 cup toor dal','2 tbsp tamarind paste','3 tomatoes, crushed',
    '2 tsp rasam powder','1 tsp cumin seeds','1 tsp black pepper',
    '4 cloves garlic, crushed','10 fresh curry leaves','1/4 cup fresh cilantro',
    '2 tbsp ghee'],
   ['Cook the dal soft and keep the thin liquid.',
    'Simmer tamarind, tomato and rasam powder for 10 minutes until the raw smell goes.',
    'Add the dal water and heat until it just froths — never let rasam boil hard.',
    'Temper cumin, pepper, garlic and curry leaves in ghee and add.',
    'Cilantro off the heat.']),
 r('Lemon Rice', L,
   ['3 cups cooked rice, cooled','2 lemons, juiced','1 tsp mustard seeds',
    '1 tbsp chana dal','2 tbsp peanuts','10 fresh curry leaves',
    '2 dried red chilies','1/2 tsp ground turmeric','3 tbsp sesame oil'],
   ['Use cold, dry, day-old rice or it turns to paste.',
    'Temper mustard seeds, dals, peanuts, chilies and curry leaves in sesame oil.',
    'Add turmeric, then the rice, folding gently with a flat spoon.',
    'Lemon juice off the heat so it stays bright.']),
 r('Curd Rice', L,
   ['3 cups cooked rice','2 cups yogurt','1/2 cup whole milk',
    '1 tsp mustard seeds','10 fresh curry leaves','1 inch fresh ginger, minced',
    '2 green chilies, slit','2 tbsp oil','1 pomegranate, seeded'],
   ['Mash the warm rice slightly with the back of a spoon.',
    'Cool completely, then fold in the yogurt and milk.',
    'Temper mustard seeds, curry leaves, ginger and chilies and stir through.',
    'Pomegranate arils on top. Best on a hot day.']),
 r('Bisi Bele Bath', D,
   ['1 cup rice','1/2 cup toor dal','1 cup mixed vegetables',
    '3 tbsp bisi bele bath powder','1 tbsp tamarind paste','1/4 cup cashews',
    '4 tbsp ghee','1 tsp mustard seeds','10 fresh curry leaves'],
   ['Cook the rice and dal together until very soft — this dish is meant to be thick and sticky.',
    'Cook the vegetables separately so they keep their shape.',
    'Combine with tamarind and the spice powder and simmer, adding water freely.',
    'Fry cashews in ghee with mustard seeds and curry leaves and pour over.']),
 r('Chettinad Chicken', D,
   ['2 lbs chicken, bone-in','1 tbsp black pepper','1 tbsp coriander seeds',
    '1 tsp cumin seeds','4 dried red chilies','1/4 cup fresh coconut, grated',
    '2 yellow onions, sliced','1 tbsp ginger garlic paste','10 fresh curry leaves',
    '3 tbsp sesame oil'],
   ['Dry-roast the pepper, coriander, cumin, chilies and coconut, then grind to a paste.',
    'Brown the onions deeply in sesame oil.',
    'Add ginger garlic paste and the ground masala; fry until it darkens and smells roasted.',
    'Add the chicken and cook in its own moisture 30 minutes.',
    'Curry leaves at the end.']),
 r('Kerala Fish Curry', D,
   ['2 lbs kingfish steaks','1 cup coconut milk','1 tbsp tamarind paste',
    '2 tsp kashmiri chili powder','1/2 tsp ground turmeric','1 tsp fenugreek seeds',
    '1 yellow onion, sliced','10 fresh curry leaves','1 inch fresh ginger, julienned',
    '3 tbsp coconut oil'],
   ['Temper fenugreek and curry leaves in coconut oil.',
    'Soften the onion and ginger, then add the ground spices and cook off the raw edge.',
    'Add tamarind and a little water and simmer 10 minutes.',
    'Slide in the fish and cook eight minutes without stirring — shake the pan instead.',
    'Add coconut milk and warm through. Never boil it after this point.',
    'It is better the next day.']),
 r('Avial', D,
   ['4 cups mixed vegetables, batons','1 cup fresh coconut, grated',
    '2 green chilies','1 tsp cumin seeds','1 cup yogurt',
    '10 fresh curry leaves','3 tbsp coconut oil','1/2 tsp ground turmeric'],
   ['Cook the vegetables with turmeric and very little water until just tender.',
    'Grind coconut, chilies and cumin to a coarse paste.',
    'Fold the paste in and cook two minutes.',
    'Off the heat, stir in yogurt, raw coconut oil and curry leaves. The raw oil is the signature.']),
 r('Vegetable Korma', D,
   ['4 cups mixed vegetables','1 cup coconut milk','1/4 cup cashews',
    '2 green chilies','1 yellow onion, sliced','1 tbsp ginger garlic paste',
    '1 tsp garam masala','10 fresh curry leaves','3 tbsp ghee',
    '1/4 cup fresh cilantro'],
   ['Grind the cashews and chilies to a smooth paste.',
    'Soften the onion in ghee without colouring, add ginger garlic paste.',
    'Add the cashew paste and cook three minutes.',
    'Add the vegetables and coconut milk and simmer until tender.',
    'Cilantro and curry leaves at the end.']),
 r('Coconut Chutney', S,
   ['1 cup fresh coconut, grated','2 tbsp roasted chana dal','2 green chilies',
    '1 inch fresh ginger','1 tsp mustard seeds','10 fresh curry leaves',
    '1 dried red chili','2 tbsp coconut oil','Salt to taste'],
   ['Grind coconut, chana dal, chilies and ginger with a little water.',
    'Keep it slightly coarse.',
    'Temper mustard seeds, curry leaves and the dried chili in coconut oil.',
    'Pour the tempering over and do not stir it in until serving.']),
 r('Tomato Chutney', S,
   ['4 tomatoes, chopped','1 yellow onion, sliced','4 dried red chilies',
    '1 tbsp chana dal','1 tbsp urad dal','1/4 tsp asafoetida',
    '10 fresh curry leaves','3 tbsp sesame oil'],
   ['Fry the dals and chilies in oil until golden.',
    'Add onion, then tomato, and cook down until jammy and the oil separates.',
    'Cool and grind coarsely.',
    'Temper curry leaves and asafoetida and stir through.']),
 r('Vada Pav', S,
   ['4 russet potatoes, boiled','2 green chilies, minced','1 tsp mustard seeds',
    '10 fresh curry leaves','1/2 tsp ground turmeric','1 cup chickpea flour',
    '4 pav buns','Oil for frying','2 tbsp garlic chutney'],
   ['Temper mustard seeds and curry leaves, add chilies and turmeric, and fold into mashed potato.',
    'Shape into balls and rest them.',
    'Make a loose chickpea-flour batter, dip, and deep-fry until golden.',
    'Split the pav, spread garlic chutney, and crush the vada inside.']),
 r('Rava Kesari', S,
   ['1 cup semolina','1 cup granulated sugar','3 cups water',
    '1/2 cup ghee','1 pinch saffron threads','4 green cardamom pods, ground',
    '2 tbsp cashews','2 tbsp raisins'],
   ['Fry the cashews and raisins in ghee and set aside.',
    'Roast the semolina in the same ghee until it smells nutty.',
    'Add boiling saffron water carefully — it will spit — and stir until it thickens.',
    'Add sugar; the mixture loosens, then tightens again. Keep going.',
    'Finish with cardamom, the nuts, and more ghee than feels sensible.']),
 r('Payasam', S,
   ['1/2 cup vermicelli','4 cups whole milk','1/2 cup jaggery',
    '3 tbsp ghee','2 tbsp cashews','2 tbsp raisins',
    '4 green cardamom pods, ground'],
   ['Fry the vermicelli, cashews and raisins in ghee separately.',
    'Simmer the vermicelli in the milk until soft.',
    'Melt the jaggery in a little water, strain it, and add off the heat.',
    'Adding jaggery to boiling milk will split it. Off the heat, always.']),
 r('Filter Coffee', S,
   ['4 tbsp coffee beans, ground fine','1 cup water, boiling',
    '2 cups whole milk','3 tbsp granulated sugar'],
   ['Pack the grounds into the filter firmly but do not tamp them hard.',
    'Pour boiling water over and let it drip for 20 minutes.',
    'Boil the milk properly, not just warm it.',
    'Mix decoction, milk and sugar, then pour between two tumblers from a height until it foams.']),
]

VEGAN = [
 r('Tofu Scramble', B,
   ['1 block firm tofu, crumbled','1/2 tsp ground turmeric','2 tbsp nutritional yeast',
    '1 red bell pepper, diced','1 yellow onion, diced','2 cups spinach',
    '1 tbsp olive oil','1/4 tsp black salt','Black pepper to taste'],
   ['Press the tofu 20 minutes, then crumble it unevenly so some pieces stay chunky.',
    'Soften the onion and pepper in oil.',
    'Add the tofu, turmeric and nutritional yeast and fry until the edges catch.',
    'Wilt the spinach through at the end.',
    'Black salt is what makes it taste of egg. Add it off the heat.']),
 r('High-Protein Overnight Oats', B,
   ['1 cup rolled oats','1 1/2 cups soy milk','1/4 cup chia seeds',
    '1 scoop pea protein powder','2 tbsp peanut butter','1 banana, sliced',
    '1 tbsp maple syrup','1 cup blueberries'],
   ['Whisk the protein powder into the soy milk first, or it clumps.',
    'Stir in the oats, chia and peanut butter.',
    'Refrigerate overnight.',
    'Top with banana and blueberries. About 32 g of protein.']),
 r('Chickpea Flour Omelette', B,
   ['1 cup chickpea flour','1 1/4 cups water','2 tbsp nutritional yeast',
    '1/4 tsp black salt','1/2 tsp baking powder','1 cup cremini mushrooms, sliced',
    '2 cups spinach','2 tbsp olive oil','Black pepper to taste'],
   ['Whisk the batter smooth and rest it 15 minutes.',
    'Cook the mushrooms hard until they brown, then the spinach.',
    'Pour the batter into an oiled pan and cook covered on low 6 minutes.',
    'Add the filling to one half and fold. Around 20 g of protein.']),
 r('Seitan Breakfast Sausage', B,
   ['1 cup vital wheat gluten','1/4 cup nutritional yeast','1 cup vegetable stock',
    '2 tbsp soy sauce','1 tsp fennel seeds','1 tsp sweet paprika',
    '1 tsp fresh sage','2 cloves garlic, minced','1 tbsp olive oil'],
   ['Mix the dry ingredients, then the wet, and knead two minutes — no longer or it turns rubbery.',
    'Roll into logs, wrap in foil, and steam 40 minutes.',
    'Cool completely; the texture sets as it cools.',
    'Slice and fry in oil until crisp. Roughly 21 g of protein per serving.']),
 r('Lentil Walnut Bolognese', L,
   ['1 cup red lentils','1 cup walnuts, chopped','1 cup mirepoix',
    '3 cloves garlic, minced','1 can crushed tomatoes','2 tbsp tomato paste',
    '1 cup vegetable stock','2 tbsp olive oil','1 lb spaghetti',
    '1/4 cup fresh basil'],
   ['Toast the walnuts and chop them to the size of mince.',
    'Soften the mirepoix slowly, then add the garlic and tomato paste and cook it dark.',
    'Add lentils, tomatoes, walnuts and stock and simmer 40 minutes.',
    'It should be thick enough to hold a spoon upright. About 24 g of protein a bowl.']),
 r('Buffalo Cauliflower Wrap', L,
   ['1 head cauliflower, florets','1/2 cup chickpea flour','1/2 cup water',
    '1/2 cup hot sauce','2 tbsp olive oil','4 tortillas',
    '2 cups romaine lettuce, shredded','1/2 cup vegan ranch','1 carrot, julienned'],
   ['Coat the florets in a chickpea-flour batter and bake at 450°F for 20 minutes.',
    'Toss in hot sauce and oil, then bake 10 minutes more so the sauce sets rather than sogs.',
    'Build the wraps with lettuce, carrot and ranch.']),
 r('Tempeh Banh Mi', L,
   ['8 oz tempeh, sliced','3 tbsp soy sauce','1 tbsp maple syrup',
    '1 baguette','1 cup daikon radish, julienned','1 carrot, julienned',
    '1/2 cup rice vinegar','1/4 cup fresh cilantro','1 jalapeño, sliced',
    '3 tbsp vegan mayonnaise'],
   ['Pickle the daikon and carrot in vinegar with a little sugar and salt for an hour.',
    'Steam the tempeh 10 minutes to take out the bitterness — this step matters.',
    'Marinate in soy and maple, then pan-fry until glazed.',
    'Build with mayonnaise, tempeh, pickles, cilantro and jalapeño. Around 22 g of protein.']),
 r('Red Lentil Dal', L,
   ['1 cup red lentils','1 yellow onion, diced','3 cloves garlic, minced',
    '1 inch fresh ginger, grated','1 tsp ground turmeric','1 tsp ground cumin',
    '1 can coconut milk','2 tbsp coconut oil','10 fresh curry leaves',
    '1/4 cup fresh cilantro'],
   ['Simmer the lentils with turmeric until they collapse, about 20 minutes.',
    'Temper cumin and curry leaves in coconut oil, then soften the onion, garlic and ginger.',
    'Stir the tempering into the dal with the coconut milk.',
    'Simmer 10 minutes more. About 18 g of protein a serving.']),
 r('Black Bean Burger', L,
   ['2 cans black beans, drained','1/2 cup rolled oats','1 yellow onion, minced',
    '3 cloves garlic, minced','1 tbsp ground cumin','2 tbsp tomato paste',
    '1/4 cup vital wheat gluten','4 burger buns','1 avocado, sliced'],
   ['Roast the beans 15 minutes to dry them out — wet beans make mushy burgers.',
    'Pulse half with the oats and aromatics; leave the rest whole for texture.',
    'Knead in the wheat gluten and chill an hour.',
    'Sear hard in a pan, 4 minutes a side. About 19 g of protein.']),
 r('Crispy Tofu Pad Thai', D,
   ['1 block extra-firm tofu, cubed','8 oz rice noodles','3 tbsp cornstarch',
    '3 tbsp tamarind paste','3 tbsp soy sauce','2 tbsp maple syrup',
    '2 cups mung bean sprouts','1/4 cup peanuts, crushed','4 green onions, sliced',
    '2 tbsp sesame oil','1 lime'],
   ['Press the tofu, toss in cornstarch, and fry until every side is crisp.',
    'Soak the noodles in hot water rather than boiling them.',
    'Whisk tamarind, soy and maple into a sauce.',
    'Stir-fry noodles and sauce hard and fast, then fold in tofu and sprouts.',
    'Peanuts, green onion and lime at the table. Around 26 g of protein.']),
 r('Chana Masala with Spinach', D,
   ['2 cans chickpeas','1 yellow onion, minced','3 tomatoes, pureed',
    '1 tbsp ginger garlic paste','2 tsp garam masala','1 tsp ground cumin',
    '4 cups spinach','3 tbsp coconut oil','1/4 cup fresh cilantro'],
   ['Brown the onion thoroughly, then the ginger garlic paste.',
    'Add tomato and spices and cook until the oil separates out.',
    'Add the chickpeas and simmer 20 minutes, crushing some against the pan.',
    'Wilt the spinach in at the end. About 20 g of protein.']),
 r('Seitan Stir-Fry', D,
   ['1 lb seitan, sliced','3 cups stir-fry vegetable mix','3 cloves garlic, minced',
    '1 inch fresh ginger, minced','3 tbsp soy sauce','1 tbsp sesame oil',
    '1 tbsp cornstarch','1 tbsp maple syrup','2 cups cooked rice'],
   ['Get the wok properly hot before anything goes in.',
    'Sear the seitan until browned at the edges, then remove it.',
    'Stir-fry the vegetables two minutes, keeping them crunchy.',
    'Return the seitan with the sauce and toss until it glazes. Roughly 34 g of protein.']),
 r('Mushroom Bourguignon', D,
   ['2 lbs cremini mushrooms, halved','1 cup mirepoix','3 cloves garlic, minced',
    '2 cups red wine','2 cups vegetable stock','2 tbsp tomato paste',
    '3 tbsp olive oil','2 tbsp all-purpose flour','2 fresh thyme sprigs',
    '4 russet potatoes, mashed'],
   ['Brown the mushrooms in batches. Crowding them steams them and you lose the whole dish.',
    'Soften the mirepoix, add garlic, tomato paste and flour.',
    'Deglaze with the wine and reduce by half.',
    'Add stock, mushrooms and thyme; simmer 40 minutes.',
    'Serve over mashed potato.']),
 r('Coconut Chickpea Curry', D,
   ['2 cans chickpeas','1 can coconut milk','1 yellow onion, diced',
    '3 cloves garlic, minced','1 tbsp red curry paste','1 red bell pepper, sliced',
    '2 cups spinach','2 tbsp coconut oil','1 lime','1/4 cup fresh cilantro'],
   ['Fry the curry paste in coconut oil for a minute until it smells fragrant.',
    'Add onion, garlic and pepper and soften.',
    'Add chickpeas and coconut milk and simmer 20 minutes.',
    'Spinach, lime and cilantro at the end.']),
 r('Tofu Tikka Masala', D,
   ['1 block extra-firm tofu, cubed','1 cup coconut yogurt','2 tbsp ginger garlic paste',
    '2 tsp garam masala','1 can crushed tomatoes','1 cup coconut milk',
    '1 yellow onion, minced','3 tbsp coconut oil','1 tbsp kasuri methi'],
   ['Press and marinate the tofu in coconut yogurt and spices two hours.',
    'Broil until charred at the corners.',
    'Cook the onion, tomatoes and remaining spices down, then blend smooth.',
    'Add coconut milk and the tofu. Crush kasuri methi over at the end. Around 24 g of protein.']),
 r('Hummus', S,
   ['2 cans chickpeas','1/2 cup tahini','3 tbsp lemon juice','2 cloves garlic',
    '1/4 tsp ground cumin','3 tbsp olive oil','1/4 tsp baking soda'],
   ['Simmer the chickpeas with baking soda 20 minutes until the skins slip off.',
    'Blend the tahini, lemon and garlic first until it seizes and goes pale.',
    'Add the warm chickpeas and blend for a full five minutes.',
    'Time in the blender is what makes it silky.']),
 r('Roasted Chickpeas', S,
   ['2 cans chickpeas','2 tbsp olive oil','1 tsp sweet paprika',
    '1 tsp ground cumin','1/2 tsp cayenne','Salt to taste'],
   ['Dry the chickpeas completely on a towel.',
    'Toss with oil and roast at 400°F for 35 minutes, shaking the tray twice.',
    'Add the spices after roasting, not before, or they scorch.']),
 r('Peanut Butter Protein Balls', S,
   ['1 cup rolled oats','1/2 cup peanut butter','1/3 cup maple syrup',
    '2 scoops pea protein powder','1/4 cup ground flaxseed','1/4 cup chocolate chips',
    '1 tsp vanilla extract'],
   ['Mix everything into a stiff dough, adding a splash of plant milk if needed.',
    'Chill 30 minutes, then roll into balls.',
    'Keep refrigerated. Around 8 g of protein each.']),
 r('Vegan Chocolate Mousse', S,
   ['1 block silken tofu','200g dark chocolate, melted','3 tbsp maple syrup',
    '1 tsp vanilla extract','Pinch of salt','1 cup raspberries'],
   ['Blend the silken tofu completely smooth before anything else goes in.',
    'Melt the chocolate and blend it in while warm.',
    'Add maple, vanilla and salt.',
    'Chill four hours. Nobody guesses it is tofu.']),
 r('Banana Nice Cream', S,
   ['4 bananas, frozen','2 tbsp peanut butter','2 tbsp cocoa powder',
    '1/4 cup soy milk','1 tsp vanilla extract'],
   ['Freeze sliced ripe bananas overnight.',
    'Blend with as little milk as the machine will tolerate.',
    'It goes gravelly, then suddenly creamy. Keep going through the gravelly stage.']),
 r('Vegan Chocolate Chip Cookies', S,
   ['2 1/4 cups all-purpose flour','1 cup vegan butter','3/4 cup brown sugar',
    '1/2 cup granulated sugar','1/4 cup aquafaba','2 tsp vanilla extract',
    '1 tsp baking soda','1 tsp salt','2 cups chocolate chips'],
   ['Whip the aquafaba to soft peaks first — it is standing in for the egg.',
    'Cream the vegan butter and sugars, then fold in the aquafaba.',
    'Add the dry ingredients and chips and chill the dough overnight.',
    'Bake at 375°F for 11 minutes.']),
 r('Chia Pudding', S,
   ['1/2 cup chia seeds','2 cups coconut milk','2 tbsp maple syrup',
    '1 tsp vanilla extract','1 cup mango, diced','2 tbsp pistachios'],
   ['Whisk the chia into the milk and wait five minutes, then whisk again — this stops clumping.',
    'Refrigerate at least four hours.',
    'Top with mango and pistachios.']),
]

VEGETARIAN = [
 r('Shakshuka', B,
   ['6 large eggs','1 can crushed tomatoes','2 red bell peppers, sliced',
    '1 yellow onion, sliced','4 cloves garlic, sliced','1 tsp ground cumin',
    '1 tsp sweet paprika','3 tbsp olive oil','1/2 cup feta cheese',
    '1/4 cup fresh cilantro'],
   ['Soften the peppers and onion slowly, a full 15 minutes.',
    'Add garlic and spices, then the tomatoes, and simmer until thick.',
    'Make wells and crack in the eggs; cover and cook until the whites just set.',
    'Feta and cilantro over the top, bread alongside.']),
 r('Greek Yogurt Protein Bowl', B,
   ['2 cups Greek yogurt','1/4 cup honey','1/2 cup granola',
    '1 cup strawberries','1/4 cup walnuts','2 tbsp chia seeds',
    '1 scoop whey protein powder'],
   ['Whisk the protein powder into the yogurt until no streaks remain.',
    'Layer with granola, berries, walnuts and chia.',
    'Honey last. Around 40 g of protein.']),
 r('Masala Omelette', B,
   ['4 large eggs','1 yellow onion, minced','2 green chilies, minced',
    '1 tomato, diced','1/4 cup fresh cilantro','1/2 tsp ground turmeric',
    '2 tbsp ghee','Black pepper to taste'],
   ['Beat the eggs hard until frothy.',
    'Fold in the onion, chilies, tomato, cilantro and turmeric.',
    'Cook in ghee on medium, pulling the edges in.',
    'Fold when the top is still slightly wet.']),
 r('Ricotta Pancakes', B,
   ['1 cup ricotta','1 cup all-purpose flour','3 large eggs, separated',
    '3/4 cup whole milk','2 tbsp granulated sugar','1 tsp baking powder',
    '1 lemon, zested','2 tbsp butter','1 cup blueberries'],
   ['Whisk the yolks, ricotta, milk and zest together.',
    'Fold in the flour, sugar and baking powder.',
    'Whip the whites to soft peaks and fold them in last — this is what makes them light.',
    'Cook gently in butter; they colour faster than ordinary pancakes.']),
 r('Halloumi and Quinoa Salad', L,
   ['250g halloumi, sliced','1 cup quinoa','1 cucumber, diced',
    '1 cup cherry tomatoes, halved','1/2 red onion, sliced thin',
    '1/4 cup fresh mint','3 tbsp olive oil','2 tbsp lemon juice',
    '1/4 cup pistachios'],
   ['Cook the quinoa and spread it out to cool so it does not steam itself soggy.',
    'Dry-fry the halloumi in a hot pan until deeply golden on both sides.',
    'Toss the quinoa with vegetables, herbs, oil and lemon.',
    'Halloumi on top while still squeaky. Roughly 28 g of protein.']),
 r('Paneer Tikka Wrap', L,
   ['400g paneer, cubed','1 cup yogurt','2 tbsp ginger garlic paste',
    '2 tsp garam masala','1 red bell pepper, chunked','1 red onion, chunked',
    '4 rotis','1/2 cup mint chutney','1 lemon'],
   ['Marinate the paneer and vegetables in spiced yogurt for an hour. No longer, or the paneer toughens.',
    'Thread onto skewers and grill until charred at the edges.',
    'Warm the rotis, spread with chutney, fill and squeeze lemon over. About 30 g of protein.']),
 r('Caprese Sandwich', L,
   ['1 ciabatta loaf','250g fresh mozzarella, sliced','2 heirloom tomatoes, sliced',
    '1/4 cup fresh basil','3 tbsp olive oil','2 tbsp balsamic vinegar',
    'Salt to taste','Black pepper to taste'],
   ['Salt the tomato slices and drain them 10 minutes.',
    'Split and lightly toast the ciabatta.',
    'Layer mozzarella, tomato and basil; oil, vinegar, salt and a lot of pepper.',
    'Press under a weight for 10 minutes.']),
 r('Egg Salad Sandwich', L,
   ['6 hard-boiled eggs','3 tbsp mayonnaise','1 tbsp Dijon mustard',
    '2 stalks celery, minced','2 tbsp fresh chives','8 slices bread',
    'Salt to taste','Black pepper to taste'],
   ['Chop the eggs coarsely — whites and yolks should stay distinguishable.',
    'Fold in the mayonnaise, mustard, celery and chives.',
    'Season well and chill an hour before making the sandwiches.']),
 r('Spinach and Feta Quiche', L,
   ['1 pie crust','6 large eggs','1 cup heavy cream','4 cups spinach',
    '1 cup feta cheese','1 yellow onion, sliced','2 tbsp butter',
    'Pinch of nutmeg','Black pepper to taste'],
   ['Blind-bake the crust 15 minutes at 400°F.',
    'Cook the spinach down and squeeze out every drop of water.',
    'Soften the onion in butter.',
    'Whisk eggs, cream and nutmeg; combine with the fillings.',
    'Bake at 350°F for 40 minutes until the centre barely trembles.']),
 r('Eggplant Parmesan', D,
   ['3 eggplants, sliced','2 cups breadcrumbs','3 large eggs, beaten',
    '1 cup all-purpose flour','1 can crushed tomatoes','500g fresh mozzarella',
    '1 1/2 cups Parmesan, grated','1/4 cup fresh basil','Oil for frying'],
   ['Salt the eggplant and drain an hour, then pat dry.',
    'Flour, egg, breadcrumb, and fry until golden.',
    'Layer with sauce and both cheeses.',
    'Bake at 375°F for 40 minutes and rest before cutting.']),
 r('Paneer Butter Masala', D,
   ['500g paneer, cubed','1 can crushed tomatoes','1/2 cup cashews',
    '1 yellow onion, chunked','1 tbsp ginger garlic paste','1 tsp garam masala',
    '1 tsp kashmiri chili powder','1/2 cup heavy cream','5 tbsp butter',
    '1 tbsp kasuri methi'],
   ['Simmer the tomatoes, cashews, onion and ginger garlic paste 20 minutes, then blend and sieve.',
    'Return to the pan with butter and spices and cook 10 minutes.',
    'Add cream and paneer and warm through gently — boiling makes paneer rubbery.',
    'Kasuri methi crushed over the top. Around 26 g of protein.']),
 r('Mushroom Risotto', D,
   ['1 1/2 cups arborio rice','1 lb cremini mushrooms, sliced',
    '1 yellow onion, minced','1/2 cup white wine','6 cups vegetable stock',
    '4 tbsp butter','1 cup Parmesan, grated','2 fresh thyme sprigs'],
   ['Brown the mushrooms in batches and set aside.',
    'Soften the onion, toast the rice, deglaze with wine.',
    'Add hot stock a ladle at a time for 18 minutes.',
    'Fold the mushrooms back in and beat in cold butter and parmesan off the heat.']),
 r('Black Bean and Sweet Potato Enchiladas', D,
   ['2 sweet potatoes, cubed','2 cans black beans','8 tortillas',
    '2 cups enchilada sauce','2 cups shredded cheese','1 yellow onion, diced',
    '1 tsp ground cumin','1 tbsp olive oil','1 avocado, sliced'],
   ['Roast the sweet potato with cumin until the edges caramelise.',
    'Mix with the beans and softened onion.',
    'Fill and roll the tortillas, seam-side down in a dish.',
    'Cover with sauce and cheese and bake at 375°F for 25 minutes.']),
 r('Palak Paneer', D,
   ['500g paneer, cubed','2 lbs spinach','1 yellow onion, minced',
    '2 green chilies','1 tbsp ginger garlic paste','1 tsp ground cumin',
    '1/2 tsp garam masala','3 tbsp ghee','1/4 cup heavy cream'],
   ['Blanch the spinach 90 seconds and shock it in ice water to keep it green.',
    'Blend coarsely with the chilies.',
    'Brown the onion, add ginger garlic paste and spices.',
    'Add the puree and cook only five minutes.',
    'Fold in paneer and cream. Around 24 g of protein.']),
 r('Stuffed Bell Peppers', D,
   ['4 red bell peppers, halved','1 cup quinoa','1 can black beans',
    '1 cup corn','1 yellow onion, diced','1 tsp ground cumin',
    '1 1/2 cups shredded cheese','1 can diced tomatoes','1/4 cup fresh cilantro'],
   ['Par-roast the pepper halves 15 minutes so they are not raw in the middle.',
    'Cook the quinoa and mix with beans, corn, onion, tomato and cumin.',
    'Fill the peppers, top with cheese, and bake 25 minutes at 375°F.']),
 r('Vegetable Lasagne', D,
   ['1 lb lasagne sheets','2 zucchini, sliced','2 eggplants, sliced',
    '500g ricotta','1 can crushed tomatoes','500g fresh mozzarella',
    '1 cup Parmesan, grated','3 tbsp olive oil','1/4 cup fresh basil'],
   ['Roast the zucchini and eggplant first to drive off water.',
    'Simmer the tomatoes with basil for 20 minutes.',
    'Layer sauce, pasta, ricotta, vegetables and mozzarella twice over.',
    'Bake covered 30 minutes, uncovered 15 more, and rest 20 minutes.']),
 r('Chickpea Shawarma Bowl', D,
   ['2 cans chickpeas','2 tsp ground cumin','2 tsp sweet paprika',
    '1 tsp ground turmeric','3 tbsp olive oil','1 cup Greek yogurt',
    '2 tbsp tahini','1 cucumber, diced','1 cup cherry tomatoes',
    '2 cups cooked rice','1 lemon'],
   ['Toss the chickpeas in oil and spices and roast at 425°F for 30 minutes until crisp.',
    'Whisk the yogurt, tahini and lemon into a sauce.',
    'Build over rice with the salad vegetables.',
    'About 25 g of protein a bowl.']),
 r('Caprese Skewers', S,
   ['250g mozzarella pearls','2 cups cherry tomatoes','1/4 cup fresh basil',
    '3 tbsp olive oil','2 tbsp balsamic glaze','Black pepper to taste'],
   ['Thread tomato, basil and mozzarella onto short skewers.',
    'Oil and glaze just before serving.',
    'Pepper over the top.']),
 r('Spinach Artichoke Dip', S,
   ['2 cups spinach','1 can artichoke hearts, chopped','8 oz cream cheese',
    '1/2 cup sour cream','1 cup Parmesan, grated','1 cup shredded cheese',
    '2 cloves garlic, minced'],
   ['Squeeze the spinach and artichokes dry.',
    'Beat the cream cheese and sour cream smooth with the garlic.',
    'Fold everything together and bake at 375°F for 25 minutes until bubbling and browned on top.']),
 r('Paneer Pakora', S,
   ['400g paneer, sliced','1 cup chickpea flour','1 tsp kashmiri chili powder',
    '1/2 tsp ground turmeric','1/4 tsp asafoetida','1/2 tsp ground cumin',
    'Oil for frying','Salt to taste'],
   ['Whisk a batter thick enough to coat the back of a spoon.',
    'Rest it 15 minutes.',
    'Dip the paneer and fry at 350°F until pale gold — too dark and the paneer squeaks.',
    'Drain on a rack and salt immediately.']),
 r('Cheese Quesadilla', S,
   ['4 tortillas','2 cups shredded cheese','1 jalapeño, sliced',
    '1/4 cup fresh cilantro','2 tbsp butter','1/2 cup sour cream'],
   ['Butter the outside of the tortilla, not the pan.',
    'Cheese, jalapeño and cilantro on one half; fold.',
    'Cook on medium-low so the cheese melts before the outside burns.',
    'Rest a minute before cutting or it all runs out.']),
 r('Cheesecake Brownies', S,
   ['1 cup butter','1 1/2 cups granulated sugar','4 large eggs',
    '1 cup cocoa powder','1 cup all-purpose flour','8 oz cream cheese',
    '1/4 cup granulated sugar','1 large egg','1 tsp vanilla extract'],
   ['Make the brownie batter and reserve a quarter of it.',
    'Beat the cream cheese with sugar, one egg and vanilla.',
    'Pour the brownie base, dollop the cheesecake and the reserved batter over it.',
    'Drag a knife through twice only — over-swirling muddies both.',
    'Bake at 350°F for 35 minutes.']),
 r('Rice Pudding', S,
   ['1 cup arborio rice','6 cups whole milk','1/2 cup granulated sugar',
    '1 tsp vanilla extract','1 cinnamon stick','1/4 cup raisins',
    'Pinch of salt','Ground cinnamon to finish'],
   ['Simmer the rice in the milk with the cinnamon stick on the lowest heat, stirring often, 45 minutes.',
    'Add sugar, vanilla, raisins and salt near the end.',
    'It thickens a lot as it cools, so stop while it still looks loose.']),
]

BOOKS = [
 ('american', 'American Classics',
  'Diner breakfasts, backyard barbecue and the desserts everyone already knows.', AMERICAN),
 ('italian', 'Italian Kitchen',
  'Regional Italian cooking with the shortcuts left out — the pasta sauces are emulsions, not cream.', ITALIAN),
 ('north-indian', 'North Indian',
  'Punjabi and Mughlai cooking: slow-browned onions, whole spices, and gravies that take their time.', NORTH_INDIAN),
 ('south-indian', 'South Indian',
  'Fermented batters, tempered oil and coconut. Tiffin, rice plates and filter coffee.', SOUTH_INDIAN),
 ('vegan', 'Vegan',
  'Entirely plant-based, and built so protein is never the afterthought — most mains clear 20 g a serving.', VEGAN),
 ('vegetarian', 'Vegetarian',
  'Eggs and dairy welcome. Paneer, halloumi and legumes carry the protein.', VEGETARIAN),
]


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def arr(items):
    """A Postgres text[] literal. Ingredient ids are minted in SQL rather than
    written out here, which keeps the seed a third of the size and readable."""
    return 'array[' + ','.join(q(i) for i in items) + ']'


def book_sql(idx, slug, name, blurb, recipes):
    fid = uuid.uuid5(NS, 'folder:' + slug)
    out = [f"-- {name}: {len(recipes)} recipes",
           'insert into "CozyCookBookSchema".folders '
           '(id, name, blurb, user_id, is_public, position) values',
           f"  ('{fid}', {q(name)}, {q(blurb)}, null, true, {idx * 1024})",
           'on conflict (id) do update set name = excluded.name, blurb = excluded.blurb;',
           '',
           'insert into "CozyCookBookSchema".recipes',
           '  (id, title, ingredients, steps, folder_id, user_id, meal, is_public, position)',
           'select r.id, r.title,',
           "  (select coalesce(jsonb_agg(jsonb_build_object("
           "'id', gen_random_uuid(), 'name', n, 'isChecked', false) order by o), '[]'::jsonb)",
           '   from unnest(r.ing) with ordinality as t(n, o)),',
           "  (select coalesce(jsonb_agg(jsonb_build_object("
           "'id', gen_random_uuid(), 'text', st, 'isChecked', false) order by o), '[]'::jsonb)",
           '   from unnest(r.steps) with ordinality as t(st, o)),',
           f"  '{fid}', null, r.meal, true, r.pos",
           'from (values']
    rows = []
    for i, rec in enumerate(recipes):
        rid = uuid.uuid5(NS, f'recipe:{slug}:{rec["title"]}')
        rows.append(f"  ('{rid}'::uuid, {q(rec['title'])}, {arr(rec['ing'])}, "
                    f"{arr(rec['steps'])}, {q(rec['meal'])}, {i * 1024})")
    out.append(',\n'.join(rows))
    out.append(') as r(id, title, ing, steps, meal, pos)')
    out.append('on conflict (id) do update set title = excluded.title, '
               'ingredients = excluded.ingredients, steps = excluded.steps, '
               'meal = excluded.meal;')
    return '\n'.join(out)


def main():
    import os
    os.makedirs('supabase/cookbooks', exist_ok=True)
    total = 0
    for idx, (slug, name, blurb, recipes) in enumerate(BOOKS):
        sql = ('-- Starter cookbook, readable by every signed-in user, owned by nobody.\n'
               '-- Generated by tools/seed_cookbooks.py - do not hand-edit.\n\n'
               + book_sql(idx, slug, name, blurb, recipes) + '\n')
        path = f'supabase/cookbooks/{idx+1:02d}_{slug}.sql'
        open(path, 'w').write(sql)
        mix = {}
        for rec in recipes:
            mix[rec['meal']] = mix.get(rec['meal'], 0) + 1
        print(f'{path}  {len(recipes):>2} recipes  {len(sql):>6} bytes  {mix}')
        total += len(recipes)
    print(f'total: {total} recipes across {len(BOOKS)} cookbooks')


if __name__ == '__main__':
    main()
